//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:13:08 AM EDT 
//


package gov.va.vba.bcdss.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Claim complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Claim">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ProfileDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ProductTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClaimDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ContentionId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContentionClassificationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContentionBeginDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Claim", propOrder = {
    "claimId",
    "profileDate",
    "productTypeCode",
    "claimDate",
    "contentionId",
    "contentionClassificationId",
    "contentionBeginDate"
})
public class Claim {

    @XmlElement(name = "ClaimId")
    protected int claimId;
    @XmlElement(name = "ProfileDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar profileDate;
    @XmlElement(name = "ProductTypeCode", required = true)
    protected String productTypeCode;
    @XmlElement(name = "ClaimDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar claimDate;
    @XmlElement(name = "ContentionId")
    protected int contentionId;
    @XmlElement(name = "ContentionClassificationId", required = true)
    protected String contentionClassificationId;
    @XmlElement(name = "ContentionBeginDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contentionBeginDate;

    /**
     * Gets the value of the claimId property.
     * 
     */
    public int getClaimId() {
        return claimId;
    }

    /**
     * Sets the value of the claimId property.
     * 
     */
    public void setClaimId(int value) {
        this.claimId = value;
    }

    /**
     * Gets the value of the profileDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProfileDate() {
        return profileDate;
    }

    /**
     * Sets the value of the profileDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProfileDate(XMLGregorianCalendar value) {
        this.profileDate = value;
    }

    /**
     * Gets the value of the productTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductTypeCode() {
        return productTypeCode;
    }

    /**
     * Sets the value of the productTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductTypeCode(String value) {
        this.productTypeCode = value;
    }

    /**
     * Gets the value of the claimDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getClaimDate() {
        return claimDate;
    }

    /**
     * Sets the value of the claimDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setClaimDate(XMLGregorianCalendar value) {
        this.claimDate = value;
    }

    /**
     * Gets the value of the contentionId property.
     * 
     */
    public int getContentionId() {
        return contentionId;
    }

    /**
     * Sets the value of the contentionId property.
     * 
     */
    public void setContentionId(int value) {
        this.contentionId = value;
    }

    /**
     * Gets the value of the contentionClassificationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentionClassificationId() {
        return contentionClassificationId;
    }

    /**
     * Sets the value of the contentionClassificationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentionClassificationId(String value) {
        this.contentionClassificationId = value;
    }

    /**
     * Gets the value of the contentionBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContentionBeginDate() {
        return contentionBeginDate;
    }

    /**
     * Sets the value of the contentionBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContentionBeginDate(XMLGregorianCalendar value) {
        this.contentionBeginDate = value;
    }

}
