//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 02:39:20 PM EDT 
//


package gov.va.vba.bcdss.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DDMModelResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DDMModelResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PattrenId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ClaimantAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ClaimCount " type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContentionCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PriorCDD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CCDAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ModelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PatternIndex" type="{http://bcdss.vba.va.gov/models}DDMPatternIndex"/>
 *         &lt;element name="DiagnosisCodeCounts" type="{http://bcdss.vba.va.gov/models}CodesCount" maxOccurs="unbounded"/>
 *         &lt;element name="ContentionCodeCounts" type="{http://bcdss.vba.va.gov/models}CodesCount" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DDMModelResponse", propOrder = {
    "pattrenId",
    "claimantAge",
    "claimCount0020",
    "contentionCount",
    "priorCDD",
    "ccdAge",
    "modelType",
    "patternIndex",
    "diagnosisCodeCounts",
    "contentionCodeCounts"
})
public class DDMModelResponse {

    @XmlElement(name = "PattrenId")
    protected int pattrenId;
    @XmlElement(name = "ClaimantAge")
    protected int claimantAge;
    @XmlElement(name = "ClaimCount ")
    protected int claimCount0020;
    @XmlElement(name = "ContentionCount")
    protected int contentionCount;
    @XmlElement(name = "PriorCDD")
    protected int priorCDD;
    @XmlElement(name = "CCDAge")
    protected int ccdAge;
    @XmlElement(name = "ModelType", required = true)
    protected String modelType;
    @XmlElement(name = "PatternIndex", required = true)
    protected DDMPatternIndex patternIndex;
    @XmlElement(name = "DiagnosisCodeCounts", required = true)
    protected List<CodesCount> diagnosisCodeCounts;
    @XmlElement(name = "ContentionCodeCounts", required = true)
    protected List<CodesCount> contentionCodeCounts;

    /**
     * Gets the value of the pattrenId property.
     * 
     */
    public int getPattrenId() {
        return pattrenId;
    }

    /**
     * Sets the value of the pattrenId property.
     * 
     */
    public void setPattrenId(int value) {
        this.pattrenId = value;
    }

    /**
     * Gets the value of the claimantAge property.
     * 
     */
    public int getClaimantAge() {
        return claimantAge;
    }

    /**
     * Sets the value of the claimantAge property.
     * 
     */
    public void setClaimantAge(int value) {
        this.claimantAge = value;
    }

    /**
     * Gets the value of the claimCount0020 property.
     * 
     */
    public int getClaimCount_0020() {
        return claimCount0020;
    }

    /**
     * Sets the value of the claimCount0020 property.
     * 
     */
    public void setClaimCount_0020(int value) {
        this.claimCount0020 = value;
    }

    /**
     * Gets the value of the contentionCount property.
     * 
     */
    public int getContentionCount() {
        return contentionCount;
    }

    /**
     * Sets the value of the contentionCount property.
     * 
     */
    public void setContentionCount(int value) {
        this.contentionCount = value;
    }

    /**
     * Gets the value of the priorCDD property.
     * 
     */
    public int getPriorCDD() {
        return priorCDD;
    }

    /**
     * Sets the value of the priorCDD property.
     * 
     */
    public void setPriorCDD(int value) {
        this.priorCDD = value;
    }

    /**
     * Gets the value of the ccdAge property.
     * 
     */
    public int getCCDAge() {
        return ccdAge;
    }

    /**
     * Sets the value of the ccdAge property.
     * 
     */
    public void setCCDAge(int value) {
        this.ccdAge = value;
    }

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelType(String value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the patternIndex property.
     * 
     * @return
     *     possible object is
     *     {@link DDMPatternIndex }
     *     
     */
    public DDMPatternIndex getPatternIndex() {
        return patternIndex;
    }

    /**
     * Sets the value of the patternIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link DDMPatternIndex }
     *     
     */
    public void setPatternIndex(DDMPatternIndex value) {
        this.patternIndex = value;
    }

    /**
     * Gets the value of the diagnosisCodeCounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosisCodeCounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosisCodeCounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodesCount }
     * 
     * 
     */
    public List<CodesCount> getDiagnosisCodeCounts() {
        if (diagnosisCodeCounts == null) {
            diagnosisCodeCounts = new ArrayList<CodesCount>();
        }
        return this.diagnosisCodeCounts;
    }

    /**
     * Gets the value of the contentionCodeCounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentionCodeCounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentionCodeCounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodesCount }
     * 
     * 
     */
    public List<CodesCount> getContentionCodeCounts() {
        if (contentionCodeCounts == null) {
            contentionCodeCounts = new ArrayList<CodesCount>();
        }
        return this.contentionCodeCounts;
    }

}
