//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:13:08 AM EDT 
//


package gov.va.vba.bcdss.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DDMModelRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DDMModelRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ModelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClaimantAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ClaimCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContentionCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PriorCDD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CDDAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContentionCodeCounts" type="{http://bcdss.vba.va.gov/models}CodesCount" maxOccurs="unbounded"/>
 *         &lt;element name="DiagnosisCodeCounts" type="{http://bcdss.vba.va.gov/models}CodesCount" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DDMModelRequest", propOrder = {
    "modelType",
    "claimantAge",
    "claimCount",
    "contentionCount",
    "priorCDD",
    "cddAge",
    "contentionCodeCounts",
    "diagnosisCodeCounts"
})
public class DDMModelRequest {

    @XmlElement(name = "ModelType", required = true)
    protected String modelType;
    @XmlElement(name = "ClaimantAge")
    protected int claimantAge;
    @XmlElement(name = "ClaimCount")
    protected int claimCount;
    @XmlElement(name = "ContentionCount")
    protected int contentionCount;
    @XmlElement(name = "PriorCDD")
    protected int priorCDD;
    @XmlElement(name = "CDDAge")
    protected int cddAge;
    @XmlElement(name = "ContentionCodeCounts", required = true)
    protected List<CodesCount> contentionCodeCounts;
    @XmlElement(name = "DiagnosisCodeCounts", required = true)
    protected List<CodesCount> diagnosisCodeCounts;

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelType(String value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the claimantAge property.
     * 
     */
    public int getClaimantAge() {
        return claimantAge;
    }

    /**
     * Sets the value of the claimantAge property.
     * 
     */
    public void setClaimantAge(int value) {
        this.claimantAge = value;
    }

    /**
     * Gets the value of the claimCount property.
     * 
     */
    public int getClaimCount() {
        return claimCount;
    }

    /**
     * Sets the value of the claimCount property.
     * 
     */
    public void setClaimCount(int value) {
        this.claimCount = value;
    }

    /**
     * Gets the value of the contentionCount property.
     * 
     */
    public int getContentionCount() {
        return contentionCount;
    }

    /**
     * Sets the value of the contentionCount property.
     * 
     */
    public void setContentionCount(int value) {
        this.contentionCount = value;
    }

    /**
     * Gets the value of the priorCDD property.
     * 
     */
    public int getPriorCDD() {
        return priorCDD;
    }

    /**
     * Sets the value of the priorCDD property.
     * 
     */
    public void setPriorCDD(int value) {
        this.priorCDD = value;
    }

    /**
     * Gets the value of the cddAge property.
     * 
     */
    public int getCDDAge() {
        return cddAge;
    }

    /**
     * Sets the value of the cddAge property.
     * 
     */
    public void setCDDAge(int value) {
        this.cddAge = value;
    }

    /**
     * Gets the value of the contentionCodeCounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentionCodeCounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentionCodeCounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodesCount }
     * 
     * 
     */
    public List<CodesCount> getContentionCodeCounts() {
        if (contentionCodeCounts == null) {
            contentionCodeCounts = new ArrayList<CodesCount>();
        }
        return this.contentionCodeCounts;
    }

    /**
     * Gets the value of the diagnosisCodeCounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosisCodeCounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosisCodeCounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodesCount }
     * 
     * 
     */
    public List<CodesCount> getDiagnosisCodeCounts() {
        if (diagnosisCodeCounts == null) {
            diagnosisCodeCounts = new ArrayList<CodesCount>();
        }
        return this.diagnosisCodeCounts;
    }

}
