//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:13:08 AM EDT 
//


package gov.va.vba.bcdss.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DDMPatternIndex complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DDMPatternIndex">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PatternId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Accuracy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CDD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NumberOfOccurances" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CatelogId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CreatedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CreatedDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DDMPatternIndex", propOrder = {
    "patternId",
    "accuracy",
    "cdd",
    "numberOfOccurances",
    "catelogId",
    "createdBy",
    "createdDate"
})
public class DDMPatternIndex {

    @XmlElement(name = "PatternId")
    protected int patternId;
    @XmlElement(name = "Accuracy")
    protected int accuracy;
    @XmlElement(name = "CDD")
    protected int cdd;
    @XmlElement(name = "NumberOfOccurances")
    protected int numberOfOccurances;
    @XmlElement(name = "CatelogId")
    protected int catelogId;
    @XmlElement(name = "CreatedBy", required = true)
    protected String createdBy;
    @XmlElement(name = "CreatedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar createdDate;

    /**
     * Gets the value of the patternId property.
     * 
     */
    public int getPatternId() {
        return patternId;
    }

    /**
     * Sets the value of the patternId property.
     * 
     */
    public void setPatternId(int value) {
        this.patternId = value;
    }

    /**
     * Gets the value of the accuracy property.
     * 
     */
    public int getAccuracy() {
        return accuracy;
    }

    /**
     * Sets the value of the accuracy property.
     * 
     */
    public void setAccuracy(int value) {
        this.accuracy = value;
    }

    /**
     * Gets the value of the cdd property.
     * 
     */
    public int getCDD() {
        return cdd;
    }

    /**
     * Sets the value of the cdd property.
     * 
     */
    public void setCDD(int value) {
        this.cdd = value;
    }

    /**
     * Gets the value of the numberOfOccurances property.
     * 
     */
    public int getNumberOfOccurances() {
        return numberOfOccurances;
    }

    /**
     * Sets the value of the numberOfOccurances property.
     * 
     */
    public void setNumberOfOccurances(int value) {
        this.numberOfOccurances = value;
    }

    /**
     * Gets the value of the catelogId property.
     * 
     */
    public int getCatelogId() {
        return catelogId;
    }

    /**
     * Sets the value of the catelogId property.
     * 
     */
    public void setCatelogId(int value) {
        this.catelogId = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

}
