//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:13:08 AM EDT 
//


package gov.va.vba.bcdss.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EarDecision complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EarDecision">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContentionLoss" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContentionTinitu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DecisionLoss" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DecisionTinitu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EarDecision", propOrder = {
    "contentionLoss",
    "contentionTinitu",
    "decisionLoss",
    "decisionTinitu"
})
public class EarDecision {

    @XmlElement(name = "ContentionLoss")
    protected int contentionLoss;
    @XmlElement(name = "ContentionTinitu")
    protected int contentionTinitu;
    @XmlElement(name = "DecisionLoss")
    protected int decisionLoss;
    @XmlElement(name = "DecisionTinitu")
    protected int decisionTinitu;

    /**
     * Gets the value of the contentionLoss property.
     * 
     */
    public int getContentionLoss() {
        return contentionLoss;
    }

    /**
     * Sets the value of the contentionLoss property.
     * 
     */
    public void setContentionLoss(int value) {
        this.contentionLoss = value;
    }

    /**
     * Gets the value of the contentionTinitu property.
     * 
     */
    public int getContentionTinitu() {
        return contentionTinitu;
    }

    /**
     * Sets the value of the contentionTinitu property.
     * 
     */
    public void setContentionTinitu(int value) {
        this.contentionTinitu = value;
    }

    /**
     * Gets the value of the decisionLoss property.
     * 
     */
    public int getDecisionLoss() {
        return decisionLoss;
    }

    /**
     * Sets the value of the decisionLoss property.
     * 
     */
    public void setDecisionLoss(int value) {
        this.decisionLoss = value;
    }

    /**
     * Gets the value of the decisionTinitu property.
     * 
     */
    public int getDecisionTinitu() {
        return decisionTinitu;
    }

    /**
     * Sets the value of the decisionTinitu property.
     * 
     */
    public void setDecisionTinitu(int value) {
        this.decisionTinitu = value;
    }

}
