//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 02:39:20 PM EDT 
//


package gov.va.vba.bcdss.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EditModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EditModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ModelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModelPatternIndex" type="{http://bcdss.vba.va.gov/models}DDMPatternIndex"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EditModel", propOrder = {
    "modelType",
    "modelPatternIndex"
})
public class EditModel {

    @XmlElement(name = "ModelType", required = true)
    protected String modelType;
    @XmlElement(name = "ModelPatternIndex", required = true)
    protected DDMPatternIndex modelPatternIndex;

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelType(String value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the modelPatternIndex property.
     * 
     * @return
     *     possible object is
     *     {@link DDMPatternIndex }
     *     
     */
    public DDMPatternIndex getModelPatternIndex() {
        return modelPatternIndex;
    }

    /**
     * Sets the value of the modelPatternIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link DDMPatternIndex }
     *     
     */
    public void setModelPatternIndex(DDMPatternIndex value) {
        this.modelPatternIndex = value;
    }

}
