//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 02:39:20 PM EDT 
//


package gov.va.vba.bcdss.models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.va.vba.bcdss.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.va.vba.bcdss.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KneeDecision }
     * 
     */
    public KneeDecision createKneeDecision() {
        return new KneeDecision();
    }

    /**
     * Create an instance of {@link RatingDecisions }
     * 
     */
    public RatingDecisions createRatingDecisions() {
        return new RatingDecisions();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link EditModel }
     * 
     */
    public EditModel createEditModel() {
        return new EditModel();
    }

    /**
     * Create an instance of {@link VeteranClaimRating }
     * 
     */
    public VeteranClaimRating createVeteranClaimRating() {
        return new VeteranClaimRating();
    }

    /**
     * Create an instance of {@link DDMModelResponse }
     * 
     */
    public DDMModelResponse createDDMModelResponse() {
        return new DDMModelResponse();
    }

    /**
     * Create an instance of {@link RatingStatus }
     * 
     */
    public RatingStatus createRatingStatus() {
        return new RatingStatus();
    }

    /**
     * Create an instance of {@link VeteranClaim }
     * 
     */
    public VeteranClaim createVeteranClaim() {
        return new VeteranClaim();
    }

    /**
     * Create an instance of {@link DDMPatternIndex }
     * 
     */
    public DDMPatternIndex createDDMPatternIndex() {
        return new DDMPatternIndex();
    }

    /**
     * Create an instance of {@link EarDecision }
     * 
     */
    public EarDecision createEarDecision() {
        return new EarDecision();
    }

    /**
     * Create an instance of {@link ClaimRating }
     * 
     */
    public ClaimRating createClaimRating() {
        return new ClaimRating();
    }

    /**
     * Create an instance of {@link CodesCount }
     * 
     */
    public CodesCount createCodesCount() {
        return new CodesCount();
    }

    /**
     * Create an instance of {@link DDMModelRequest }
     * 
     */
    public DDMModelRequest createDDMModelRequest() {
        return new DDMModelRequest();
    }

    /**
     * Create an instance of {@link Veteran }
     * 
     */
    public Veteran createVeteran() {
        return new Veteran();
    }

    /**
     * Create an instance of {@link Claim }
     * 
     */
    public Claim createClaim() {
        return new Claim();
    }

}
