//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 02:39:20 PM EDT 
//


package gov.va.vba.bcdss.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Rating complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rating">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimantAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PromulgationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="RecentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ContationCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PriorCDD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="QuantPriorCDD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CurrentCDD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ClaimAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CDDAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ClaimCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ProcessId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PatternId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ProcessDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ModelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModelContentionCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="QuantCDD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RatingDecisions" type="{http://bcdss.vba.va.gov/models}RatingDecisions"/>
 *         &lt;element name="Status" type="{http://bcdss.vba.va.gov/models}RatingStatus" maxOccurs="unbounded"/>
 *         &lt;element name="DiagnosisCodeCounts" type="{http://bcdss.vba.va.gov/models}CodesCount" maxOccurs="unbounded"/>
 *         &lt;element name="ContentionsCodeCounts" type="{http://bcdss.vba.va.gov/models}CodesCount" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rating", propOrder = {
    "claimantAge",
    "promulgationDate",
    "recentDate",
    "contationCount",
    "priorCDD",
    "quantPriorCDD",
    "currentCDD",
    "claimAge",
    "cddAge",
    "claimCount",
    "processId",
    "patternId",
    "processDate",
    "modelType",
    "modelContentionCount",
    "quantCDD",
    "ratingDecisions",
    "status",
    "diagnosisCodeCounts",
    "contentionsCodeCounts"
})
public class Rating {

    @XmlElement(name = "ClaimantAge")
    protected int claimantAge;
    @XmlElement(name = "PromulgationDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar promulgationDate;
    @XmlElement(name = "RecentDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar recentDate;
    @XmlElement(name = "ContationCount")
    protected int contationCount;
    @XmlElement(name = "PriorCDD")
    protected int priorCDD;
    @XmlElement(name = "QuantPriorCDD")
    protected int quantPriorCDD;
    @XmlElement(name = "CurrentCDD")
    protected int currentCDD;
    @XmlElement(name = "ClaimAge")
    protected int claimAge;
    @XmlElement(name = "CDDAge")
    protected int cddAge;
    @XmlElement(name = "ClaimCount")
    protected int claimCount;
    @XmlElement(name = "ProcessId")
    protected int processId;
    @XmlElement(name = "PatternId")
    protected int patternId;
    @XmlElement(name = "ProcessDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar processDate;
    @XmlElement(name = "ModelType", required = true)
    protected String modelType;
    @XmlElement(name = "ModelContentionCount")
    protected int modelContentionCount;
    @XmlElement(name = "QuantCDD")
    protected int quantCDD;
    @XmlElement(name = "RatingDecisions", required = true)
    protected RatingDecisions ratingDecisions;
    @XmlElement(name = "Status", required = true)
    protected List<RatingStatus> status;
    @XmlElement(name = "DiagnosisCodeCounts", required = true)
    protected List<CodesCount> diagnosisCodeCounts;
    @XmlElement(name = "ContentionsCodeCounts", required = true)
    protected List<CodesCount> contentionsCodeCounts;

    /**
     * Gets the value of the claimantAge property.
     * 
     */
    public int getClaimantAge() {
        return claimantAge;
    }

    /**
     * Sets the value of the claimantAge property.
     * 
     */
    public void setClaimantAge(int value) {
        this.claimantAge = value;
    }

    /**
     * Gets the value of the promulgationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPromulgationDate() {
        return promulgationDate;
    }

    /**
     * Sets the value of the promulgationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPromulgationDate(XMLGregorianCalendar value) {
        this.promulgationDate = value;
    }

    /**
     * Gets the value of the recentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRecentDate() {
        return recentDate;
    }

    /**
     * Sets the value of the recentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRecentDate(XMLGregorianCalendar value) {
        this.recentDate = value;
    }

    /**
     * Gets the value of the contationCount property.
     * 
     */
    public int getContationCount() {
        return contationCount;
    }

    /**
     * Sets the value of the contationCount property.
     * 
     */
    public void setContationCount(int value) {
        this.contationCount = value;
    }

    /**
     * Gets the value of the priorCDD property.
     * 
     */
    public int getPriorCDD() {
        return priorCDD;
    }

    /**
     * Sets the value of the priorCDD property.
     * 
     */
    public void setPriorCDD(int value) {
        this.priorCDD = value;
    }

    /**
     * Gets the value of the quantPriorCDD property.
     * 
     */
    public int getQuantPriorCDD() {
        return quantPriorCDD;
    }

    /**
     * Sets the value of the quantPriorCDD property.
     * 
     */
    public void setQuantPriorCDD(int value) {
        this.quantPriorCDD = value;
    }

    /**
     * Gets the value of the currentCDD property.
     * 
     */
    public int getCurrentCDD() {
        return currentCDD;
    }

    /**
     * Sets the value of the currentCDD property.
     * 
     */
    public void setCurrentCDD(int value) {
        this.currentCDD = value;
    }

    /**
     * Gets the value of the claimAge property.
     * 
     */
    public int getClaimAge() {
        return claimAge;
    }

    /**
     * Sets the value of the claimAge property.
     * 
     */
    public void setClaimAge(int value) {
        this.claimAge = value;
    }

    /**
     * Gets the value of the cddAge property.
     * 
     */
    public int getCDDAge() {
        return cddAge;
    }

    /**
     * Sets the value of the cddAge property.
     * 
     */
    public void setCDDAge(int value) {
        this.cddAge = value;
    }

    /**
     * Gets the value of the claimCount property.
     * 
     */
    public int getClaimCount() {
        return claimCount;
    }

    /**
     * Sets the value of the claimCount property.
     * 
     */
    public void setClaimCount(int value) {
        this.claimCount = value;
    }

    /**
     * Gets the value of the processId property.
     * 
     */
    public int getProcessId() {
        return processId;
    }

    /**
     * Sets the value of the processId property.
     * 
     */
    public void setProcessId(int value) {
        this.processId = value;
    }

    /**
     * Gets the value of the patternId property.
     * 
     */
    public int getPatternId() {
        return patternId;
    }

    /**
     * Sets the value of the patternId property.
     * 
     */
    public void setPatternId(int value) {
        this.patternId = value;
    }

    /**
     * Gets the value of the processDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessDate() {
        return processDate;
    }

    /**
     * Sets the value of the processDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessDate(XMLGregorianCalendar value) {
        this.processDate = value;
    }

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelType(String value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the modelContentionCount property.
     * 
     */
    public int getModelContentionCount() {
        return modelContentionCount;
    }

    /**
     * Sets the value of the modelContentionCount property.
     * 
     */
    public void setModelContentionCount(int value) {
        this.modelContentionCount = value;
    }

    /**
     * Gets the value of the quantCDD property.
     * 
     */
    public int getQuantCDD() {
        return quantCDD;
    }

    /**
     * Sets the value of the quantCDD property.
     * 
     */
    public void setQuantCDD(int value) {
        this.quantCDD = value;
    }

    /**
     * Gets the value of the ratingDecisions property.
     * 
     * @return
     *     possible object is
     *     {@link RatingDecisions }
     *     
     */
    public RatingDecisions getRatingDecisions() {
        return ratingDecisions;
    }

    /**
     * Sets the value of the ratingDecisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingDecisions }
     *     
     */
    public void setRatingDecisions(RatingDecisions value) {
        this.ratingDecisions = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the status property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RatingStatus }
     * 
     * 
     */
    public List<RatingStatus> getStatus() {
        if (status == null) {
            status = new ArrayList<RatingStatus>();
        }
        return this.status;
    }

    /**
     * Gets the value of the diagnosisCodeCounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosisCodeCounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosisCodeCounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodesCount }
     * 
     * 
     */
    public List<CodesCount> getDiagnosisCodeCounts() {
        if (diagnosisCodeCounts == null) {
            diagnosisCodeCounts = new ArrayList<CodesCount>();
        }
        return this.diagnosisCodeCounts;
    }

    /**
     * Gets the value of the contentionsCodeCounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentionsCodeCounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentionsCodeCounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodesCount }
     * 
     * 
     */
    public List<CodesCount> getContentionsCodeCounts() {
        if (contentionsCodeCounts == null) {
            contentionsCodeCounts = new ArrayList<CodesCount>();
        }
        return this.contentionsCodeCounts;
    }

}
