//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 02:39:20 PM EDT 
//


package gov.va.vba.bcdss.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RatingDecisions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatingDecisions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProcessId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="KneeRatings" type="{http://bcdss.vba.va.gov/models}KneeDecision"/>
 *         &lt;element name="EarRatings" type="{http://bcdss.vba.va.gov/models}EarDecision"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatingDecisions", propOrder = {
    "processId",
    "kneeRatings",
    "earRatings"
})
public class RatingDecisions {

    @XmlElement(name = "ProcessId")
    protected int processId;
    @XmlElement(name = "KneeRatings", required = true)
    protected KneeDecision kneeRatings;
    @XmlElement(name = "EarRatings", required = true)
    protected EarDecision earRatings;

    /**
     * Gets the value of the processId property.
     * 
     */
    public int getProcessId() {
        return processId;
    }

    /**
     * Sets the value of the processId property.
     * 
     */
    public void setProcessId(int value) {
        this.processId = value;
    }

    /**
     * Gets the value of the kneeRatings property.
     * 
     * @return
     *     possible object is
     *     {@link KneeDecision }
     *     
     */
    public KneeDecision getKneeRatings() {
        return kneeRatings;
    }

    /**
     * Sets the value of the kneeRatings property.
     * 
     * @param value
     *     allowed object is
     *     {@link KneeDecision }
     *     
     */
    public void setKneeRatings(KneeDecision value) {
        this.kneeRatings = value;
    }

    /**
     * Gets the value of the earRatings property.
     * 
     * @return
     *     possible object is
     *     {@link EarDecision }
     *     
     */
    public EarDecision getEarRatings() {
        return earRatings;
    }

    /**
     * Sets the value of the earRatings property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarDecision }
     *     
     */
    public void setEarRatings(EarDecision value) {
        this.earRatings = value;
    }

}
