delete from BCDSS.MODEL_RATING_RESULTS;
delete from BCDSS.MODEL_RATING_RESULTS_CNTNT;
delete from BCDSS.MODEL_RATING_RESULTS_DIAG;
delete from BCDSS.MODEL_RATING_RESULTS_STATUS;

alter table bcdss.DDM_MODEL_PATTERN_INDX drop CONSTRAINT R_3;