package gov.va.vba.persistence.entity;
// Generated Nov 17, 2016 12:12:28 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelRatingResultsCntntId generated by hbm2java
 */
@Embeddable
public class ModelRatingResultsCntntId implements java.io.Serializable {

	private BigDecimal cntntId;
	private BigDecimal processId;

	public ModelRatingResultsCntntId() {
	}

	public ModelRatingResultsCntntId(BigDecimal cntntId, BigDecimal processId) {
		this.cntntId = cntntId;
		this.processId = processId;
	}

	@Column(name = "CNTNT_ID")
	public BigDecimal getCntntId() {
		return this.cntntId;
	}

	public void setCntntId(BigDecimal cntntId) {
		this.cntntId = cntntId;
	}

	@Column(name = "PROCESS_ID")
	public BigDecimal getProcessId() {
		return this.processId;
	}

	public void setProcessId(BigDecimal processId) {
		this.processId = processId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelRatingResultsCntntId))
			return false;
		ModelRatingResultsCntntId castOther = (ModelRatingResultsCntntId) other;

		return ((this.getCntntId() == castOther.getCntntId()) || (this.getCntntId() != null
				&& castOther.getCntntId() != null && this.getCntntId().equals(castOther.getCntntId())))
				&& ((this.getProcessId() == castOther.getProcessId()) || (this.getProcessId() != null
						&& castOther.getProcessId() != null && this.getProcessId().equals(castOther.getProcessId())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (getCntntId() == null ? 0 : this.getCntntId().hashCode());
		result = 37 * result + (getProcessId() == null ? 0 : this.getProcessId().hashCode());
		return result;
	}

}
