--------------------------------------------------------
--  File created - Thursday-March-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BCDSS_HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "BCDSS"."BCDSS_HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1264 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DDM_CNTNT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BCDSS"."DDM_CNTNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DDM_DIAG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BCDSS"."DDM_DIAG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AH4929_PERSON
--------------------------------------------------------

  CREATE TABLE "BCDSS"."AH4929_PERSON" 
   (	"PTCPNT_VET_ID" NUMBER(15,0), 
	"GENDER" VARCHAR2(9 BYTE), 
	"DOB" VARCHAR2(4 BYTE), 
	"DOD" VARCHAR2(4 BYTE), 
	"STATE_CODE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AH4929_RATING_CORP_CLAIM
--------------------------------------------------------

  CREATE TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM" 
   (	"PTCPNT_VET_ID" NUMBER(15,0), 
	"PRFIL_DT" DATE, 
	"BNFT_CLAIM_ID" NUMBER(15,0), 
	"END_PRDCT_TYPE_CD" VARCHAR2(12 BYTE), 
	"DATE_OF_CLAIM" DATE, 
	"PAYEE_TYPE_CD" VARCHAR2(12 BYTE), 
	"BNFT_CLAIM_TYPE_CD" VARCHAR2(12 BYTE), 
	"CLAIM_LABEL" VARCHAR2(50 BYTE), 
	"STATUS_TYPE_CD" VARCHAR2(12 BYTE), 
	"CLAIM_RO_NUMBER" NUMBER, 
	"CLAIM_RO_NAME" VARCHAR2(100 BYTE), 
	"CNTNTN_ID" VARCHAR2(40 BYTE), 
	"CNTNTN_CLSFCN_ID" NUMBER(15,0), 
	"CNTNTN_TYPE_CD" VARCHAR2(12 BYTE), 
	"CNTNTN_CLMANT_TXT" VARCHAR2(255 BYTE), 
	"CNTNTN_MED_IND" VARCHAR2(1 BYTE), 
	"CNTNTN_WELL_GRNDED_APLCBL_IND" VARCHAR2(1 BYTE), 
	"CNTNTN_BEGIN_DT" DATE, 
	"CNTNTN_SPECL_ISSUE_ID" VARCHAR2(40 BYTE), 
	"CNTNTN_SPECL_ISSUE_TYPE_CD" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM"  IS 'snapshot table for snapshot ADHOC_DMT_RECURR.AH4929_RATING_CORP_CLAIM';
--------------------------------------------------------
--  DDL for Table AH4929_RATING_DECISION
--------------------------------------------------------

  CREATE TABLE "BCDSS"."AH4929_RATING_DECISION" 
   (	"PTCPNT_VET_ID" NUMBER(*,0), 
	"PRFIL_DT" DATE, 
	"INACTV_DT" DATE, 
	"SYSTEM_TYPE_CD" VARCHAR2(12 BYTE), 
	"RATING_DECN_ID" NUMBER(*,0), 
	"POA" VARCHAR2(200 BYTE), 
	"PRMLGN_DT" DATE, 
	"RATING_DT" DATE, 
	"VBMS_R_IND" VARCHAR2(1 BYTE), 
	"JRSDTN_TXT" VARCHAR2(50 BYTE), 
	"RATING_RCVD_DT" DATE, 
	"STATION_NUMBER" NUMBER, 
	"STATION_NAME" VARCHAR2(100 BYTE), 
	"MILITARY_SVC_PERIOD_CODE" VARCHAR2(12 BYTE), 
	"MILITARY_SVC_PERIOD_DESC" VARCHAR2(250 BYTE), 
	"RATING_DECN_TYPE_CD" VARCHAR2(15 BYTE), 
	"RATING_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"NARRATIVE_CODESHEET_IND" VARCHAR2(1 BYTE), 
	"ISSUE_TXT" VARCHAR2(2048 BYTE), 
	"DECN_TXT" VARCHAR2(2048 BYTE), 
	"DSBLTY_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"DSBLTY_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"DSBLTY_DECN_BASIS_TYPE_CD" VARCHAR2(12 BYTE), 
	"DSBLTY_DECN_BASIS_TYPE_DESC" VARCHAR2(50 BYTE), 
	"BLATRL_TYPE_CD" VARCHAR2(12 BYTE), 
	"BLATRL_TYPE_DESC" VARCHAR2(50 BYTE), 
	"DIAGNOSIS_CODE" VARCHAR2(12 BYTE), 
	"DIAGNOSIS_DESCRIPTION" VARCHAR2(250 BYTE), 
	"DSBLTY_ID" NUMBER(*,0), 
	"DSBLTY_DT" DATE, 
	"DGNSTC_TXT" VARCHAR2(300 BYTE), 
	"RELATD_DSBLTY_ID" NUMBER(*,0), 
	"RELATD_DSBLTY_DT" DATE, 
	"SPLMTL_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"HYPNTD_DGNSTC_TYPE_CD" VARCHAR2(12 BYTE), 
	"SHED_TYPE_CD" VARCHAR2(12 BYTE), 
	"PRGRPH_TYPE_CD" VARCHAR2(12 BYTE), 
	"PRCNT_NBR" VARCHAR2(10 BYTE), 
	"MAJOR_IND" VARCHAR2(1 BYTE), 
	"COMBAT_IND" VARCHAR2(1 BYTE), 
	"PREV_EVALTN_IND" VARCHAR2(1 BYTE), 
	"BEGIN_DT" DATE, 
	"END_DT" DATE, 
	"FUTURE_EXAM_DT" DATE, 
	"STATIC_IND" VARCHAR2(1 BYTE), 
	"ANCILY_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"ANCILY_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"CMPTNY_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"CMPTNY_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"DENTAL_SVC_CNECTD_IND" VARCHAR2(1 BYTE), 
	"INDVDL_UNEMPL_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"INDVDL_UNEMPL_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"PERMNT_TOTAL_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"PERMNT_TOTAL_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SC_DEATH_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"SC_DEATH_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SMP_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"SMP_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SPECL_PRVSN_LAW_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"SPECL_PRVSN_LAW_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SMC_TYPE_CD" VARCHAR2(12 BYTE), 
	"SMC_TYPE_DESC" VARCHAR2(50 BYTE), 
	"HSPTL_SMC_TYPE_CD" VARCHAR2(12 BYTE), 
	"HSPTL_SMC_TYPE_DESC" VARCHAR2(50 BYTE), 
	"LOSS_USE_TYPE_CD" VARCHAR2(12 BYTE), 
	"LOSS_USE_TYPE_DESC" VARCHAR2(50 BYTE), 
	"ANTMCL_LOSS_TYPE_CD" VARCHAR2(12 BYTE), 
	"ANTMCL_LOSS_TYPE_DESC" VARCHAR2(50 BYTE), 
	"OTHER_LOSS_TYPE_CD" VARCHAR2(12 BYTE), 
	"OTHER_LOSS_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SMC_PRGRPH_KEY_CD" VARCHAR2(12 BYTE), 
	"SMC_PRGRPH_TXT" VARCHAR2(2000 BYTE), 
	"RELATD_DGNSTC_TXT" VARCHAR2(300 BYTE), 
	"FULL_DGNSTC_TXT" VARCHAR2(617 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARTITION BY HASH ("PTCPNT_VET_ID") 
 (PARTITION "P1" 
   TABLESPACE "USERS" ) ;
--------------------------------------------------------
--  DDL for Table AH4929_RATING_DECISION_OLD
--------------------------------------------------------

  CREATE TABLE "BCDSS"."AH4929_RATING_DECISION_OLD" 
   (	"PTCPNT_VET_ID" NUMBER(*,0), 
	"PRFIL_DT" DATE, 
	"INACTV_DT" DATE, 
	"SYSTEM_TYPE_CD" VARCHAR2(12 BYTE), 
	"RATING_DECN_ID" NUMBER(*,0), 
	"POA" VARCHAR2(200 BYTE), 
	"PRMLGN_DT" DATE, 
	"RATING_DT" DATE, 
	"VBMS_R_IND" VARCHAR2(1 BYTE), 
	"JRSDTN_TXT" VARCHAR2(50 BYTE), 
	"RATING_RCVD_DT" DATE, 
	"STATION_NUMBER" NUMBER, 
	"STATION_NAME" VARCHAR2(100 BYTE), 
	"MILITARY_SVC_PERIOD_CODE" VARCHAR2(12 BYTE), 
	"MILITARY_SVC_PERIOD_DESC" VARCHAR2(250 BYTE), 
	"RATING_DECN_TYPE_CD" VARCHAR2(15 BYTE), 
	"RATING_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"NARRATIVE_CODESHEET_IND" VARCHAR2(1 BYTE), 
	"ISSUE_TXT" VARCHAR2(2048 BYTE), 
	"DECN_TXT" VARCHAR2(2048 BYTE), 
	"DSBLTY_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"DSBLTY_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"DSBLTY_DECN_BASIS_TYPE_CD" VARCHAR2(12 BYTE), 
	"DSBLTY_DECN_BASIS_TYPE_DESC" VARCHAR2(50 BYTE), 
	"BLATRL_TYPE_CD" VARCHAR2(12 BYTE), 
	"BLATRL_TYPE_DESC" VARCHAR2(50 BYTE), 
	"DIAGNOSIS_CODE" VARCHAR2(12 BYTE), 
	"DIAGNOSIS_DESCRIPTION" VARCHAR2(250 BYTE), 
	"DSBLTY_ID" NUMBER(*,0), 
	"DSBLTY_DT" DATE, 
	"DGNSTC_TXT" VARCHAR2(300 BYTE), 
	"RELATD_DSBLTY_ID" NUMBER(*,0), 
	"RELATD_DSBLTY_DT" DATE, 
	"RELATD_DGNSTC_TXT" VARCHAR2(300 BYTE), 
	"FULL_DGNSTC_TXT" VARCHAR2(617 BYTE), 
	"SPLMTL_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"HYPNTD_DGNSTC_TYPE_CD" VARCHAR2(12 BYTE), 
	"SHED_TYPE_CD" VARCHAR2(12 BYTE), 
	"PRGRPH_TYPE_CD" VARCHAR2(12 BYTE), 
	"PRCNT_NBR" VARCHAR2(10 BYTE), 
	"MAJOR_IND" VARCHAR2(1 BYTE), 
	"COMBAT_IND" VARCHAR2(1 BYTE), 
	"PREV_EVALTN_IND" VARCHAR2(1 BYTE), 
	"BEGIN_DT" DATE, 
	"END_DT" DATE, 
	"FUTURE_EXAM_DT" DATE, 
	"STATIC_IND" VARCHAR2(1 BYTE), 
	"ANCILY_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"ANCILY_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"CMPTNY_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"CMPTNY_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"DENTAL_SVC_CNECTD_IND" VARCHAR2(1 BYTE), 
	"INDVDL_UNEMPL_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"INDVDL_UNEMPL_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"PERMNT_TOTAL_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"PERMNT_TOTAL_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SC_DEATH_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"SC_DEATH_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SMP_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"SMP_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SPECL_PRVSN_LAW_DECN_TYPE_CD" VARCHAR2(12 BYTE), 
	"SPECL_PRVSN_LAW_DECN_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SMC_TYPE_CD" VARCHAR2(12 BYTE), 
	"SMC_TYPE_DESC" VARCHAR2(50 BYTE), 
	"HSPTL_SMC_TYPE_CD" VARCHAR2(12 BYTE), 
	"HSPTL_SMC_TYPE_DESC" VARCHAR2(50 BYTE), 
	"LOSS_USE_TYPE_CD" VARCHAR2(12 BYTE), 
	"LOSS_USE_TYPE_DESC" VARCHAR2(50 BYTE), 
	"ANTMCL_LOSS_TYPE_CD" VARCHAR2(12 BYTE), 
	"ANTMCL_LOSS_TYPE_DESC" VARCHAR2(50 BYTE), 
	"OTHER_LOSS_TYPE_CD" VARCHAR2(12 BYTE), 
	"OTHER_LOSS_TYPE_DESC" VARCHAR2(50 BYTE), 
	"SMC_PRGRPH_KEY_CD" VARCHAR2(12 BYTE), 
	"SMC_PRGRPH_TXT" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON TABLE "BCDSS"."AH4929_RATING_DECISION_OLD"  IS 'snapshot table for snapshot ADHOC_DMT_RECURR.AH4929_RATING_DECISION';
--------------------------------------------------------
--  DDL for Table AUDT_EVENT
--------------------------------------------------------

  CREATE TABLE "BCDSS"."AUDT_EVENT" 
   (	"EVENT_ID" NUMBER(38,0), 
	"PRINCIPAL" VARCHAR2(255 BYTE), 
	"EVENT_DATE" TIMESTAMP (6), 
	"EVENT_TYPE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUDT_EVENT_DATA
--------------------------------------------------------

  CREATE TABLE "BCDSS"."AUDT_EVENT_DATA" 
   (	"EVENT_ID" NUMBER(38,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"VALUE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUDT_PERSISTENT_TOKEN
--------------------------------------------------------

  CREATE TABLE "BCDSS"."AUDT_PERSISTENT_TOKEN" 
   (	"SERIES" VARCHAR2(255 BYTE), 
	"USER_ID" NUMBER(38,0), 
	"TOKEN_VALUE" VARCHAR2(255 BYTE), 
	"TOKEN_DATE" DATE, 
	"IP_ADDRESS" VARCHAR2(39 BYTE), 
	"USER_AGENT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BULK_PROCESS_REQUEST
--------------------------------------------------------

  CREATE TABLE "BCDSS"."BULK_PROCESS_REQUEST" 
   (	"REQUEST_ID" NUMBER, 
	"REQUEST_DATE" TIMESTAMP (6), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"MODEL_TYPE" VARCHAR2(50 BYTE), 
	"RO_NUMBER" NUMBER, 
	"CRTD_BY" VARCHAR2(50 BYTE), 
	"REQUEST_STATUS" VARCHAR2(50 BYTE), 
	"COMPLETED_DATE" TIMESTAMP (6), 
	"RECORD_COUNT" NUMBER, 
	"NOTES" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DATABASECHANGELOG
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DATABASECHANGELOG" 
   (	"ID" VARCHAR2(255 BYTE), 
	"AUTHOR" VARCHAR2(255 BYTE), 
	"FILENAME" VARCHAR2(255 BYTE), 
	"DATEEXECUTED" TIMESTAMP (6), 
	"ORDEREXECUTED" NUMBER(10,0), 
	"EXECTYPE" VARCHAR2(10 BYTE), 
	"MD5SUM" VARCHAR2(35 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"TAG" VARCHAR2(255 BYTE), 
	"LIQUIBASE" VARCHAR2(20 BYTE), 
	"CONTEXTS" VARCHAR2(255 BYTE), 
	"LABELS" VARCHAR2(255 BYTE), 
	"DEPLOYMENT_ID" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DATABASECHANGELOGLOCK
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DATABASECHANGELOGLOCK" 
   (	"ID" NUMBER(10,0), 
	"LOCKED" NUMBER(1,0), 
	"LOCKGRANTED" TIMESTAMP (6), 
	"LOCKEDBY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DDM_CNTNT
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DDM_CNTNT" 
   (	"CNTNT_ID" NUMBER, 
	"CTLG_ID" NUMBER, 
	"CNTNT_CD" NUMBER, 
	"MODEL_TYPE" VARCHAR2(50 BYTE), 
	"CNTNT_CD_DESC" VARCHAR2(500 BYTE), 
	"CRTD_BY" VARCHAR2(50 BYTE), 
	"CRTD_DTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DDM_CTLG
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DDM_CTLG" 
   (	"CTLG_ID" NUMBER, 
	"CTLG_DESC" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DDM_DIAG
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DDM_DIAG" 
   (	"DIAG_ID" NUMBER, 
	"CTLG_ID" NUMBER, 
	"DIAG_CD" NUMBER, 
	"DIAG_CD_DESC" VARCHAR2(500 BYTE), 
	"CRTD_BY" VARCHAR2(50 BYTE), 
	"CRTD_DTM" DATE, 
	"MODEL_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DDM_MODEL_CNTNT
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DDM_MODEL_CNTNT" 
   (	"PATTERN_ID" NUMBER, 
	"CNTNT_CD" NUMBER, 
	"COUNT" NUMBER, 
	"MODEL_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DDM_MODEL_DIAG
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DDM_MODEL_DIAG" 
   (	"PATTERN_ID" NUMBER, 
	"DIAG_CD" NUMBER, 
	"COUNT" NUMBER, 
	"MODEL_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DDM_MODEL_PATTERN
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DDM_MODEL_PATTERN" 
   (	"PATTERN_ID" NUMBER, 
	"MODEL_TYPE" VARCHAR2(50 BYTE), 
	"CLAIMANT_AGE" NUMBER, 
	"CLAIM_COUNT" NUMBER, 
	"CONTENTION_COUNT" NUMBER, 
	"PRIOR_CDD" NUMBER, 
	"CDD_AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DDM_MODEL_PATTERN_INDX
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DDM_MODEL_PATTERN_INDX" 
   (	"PATTERN_ID" NUMBER, 
	"ACCURACY" NUMBER, 
	"CDD" NUMBER, 
	"PATTERN_INDX_NUMBER" NUMBER, 
	"CRTD_BY" VARCHAR2(50 BYTE), 
	"CRTD_DTM" DATE, 
	"CTLG_ID" NUMBER, 
	"MODEL_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DR$IX_RATING_CORP_CLAIM_03$I
--------------------------------------------------------

  CREATE TABLE "BCDSS"."DR$IX_RATING_CORP_CLAIM_03$I" 
   (	"DR$TOKEN" VARCHAR2(64 BYTE), 
	"DR$TOKEN_TYPE" NUMBER(3,0), 
	"DR$ROWID" ROWID, 
	"DR$TOKEN_INFO" RAW(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  MONITORING ;
--------------------------------------------------------
--  DDL for Table MODEL_RATING_RESULTS
--------------------------------------------------------

  CREATE TABLE "BCDSS"."MODEL_RATING_RESULTS" 
   (	"PROCESS_ID" NUMBER, 
	"PTCPNT_VET_ID" NUMBER, 
	"PATTERN_ID" NUMBER, 
	"PROCESS_DATE" DATE, 
	"CLAIM_ID" NUMBER, 
	"CLAIMANT_AGE" NUMBER, 
	"DOB" DATE, 
	"END_PRODUCT_CODE" VARCHAR2(50 BYTE), 
	"RO_NUMBER" NUMBER, 
	"CLAIM_DATE" DATE, 
	"PROFILE_DATE" DATE, 
	"PROMULGATION_DATE" DATE, 
	"RECENT_DATE" DATE, 
	"MODEL_TYPE" VARCHAR2(50 BYTE), 
	"MODEL_CONTENTION_COUNT" NUMBER, 
	"CONTENTION_COUNT" NUMBER, 
	"PRIOR_CDD" NUMBER, 
	"QUANT_PRIOR_CDD" NUMBER, 
	"CURR_CDD" NUMBER, 
	"QUANT_CDD" NUMBER, 
	"CLAIM_AGE" NUMBER, 
	"CDD_AGE" NUMBER, 
	"CLAIM_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MODEL_RATING_RESULTS_CNTNT
--------------------------------------------------------

  CREATE TABLE "BCDSS"."MODEL_RATING_RESULTS_CNTNT" 
   (	"CNTNT_CD" NUMBER, 
	"PROCESS_ID" NUMBER, 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MODEL_RATING_RESULTS_DIAG
--------------------------------------------------------

  CREATE TABLE "BCDSS"."MODEL_RATING_RESULTS_DIAG" 
   (	"DIAG_CD" NUMBER, 
	"PROCESS_ID" NUMBER, 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MODEL_RATING_RESULTS_STATUS
--------------------------------------------------------

  CREATE TABLE "BCDSS"."MODEL_RATING_RESULTS_STATUS" 
   (	"PROCESS_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(50 BYTE), 
	"REASON" VARCHAR2(50 BYTE), 
	"CRTD_BY" VARCHAR2(50 BYTE), 
	"CRTD_DTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEC_APP_ROLE
--------------------------------------------------------

  CREATE TABLE "BCDSS"."SEC_APP_ROLE" 
   (	"ROLE_ID" NUMBER(38,0), 
	"ROLE_NM" VARCHAR2(25 BYTE), 
	"ROLE_DSCN" VARCHAR2(100 BYTE), 
	"CRDT_BY" VARCHAR2(50 BYTE), 
	"CRDT_DTM" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDT_BY" VARCHAR2(25 BYTE), 
	"UPDT_DTM" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEC_APP_ROLE_PERM
--------------------------------------------------------

  CREATE TABLE "BCDSS"."SEC_APP_ROLE_PERM" 
   (	"ROLE_ID" NUMBER(38,0), 
	"PERM_ID" NUMBER(38,0), 
	"ASSGN_PERM" VARCHAR2(25 BYTE), 
	"CRDT_BY" VARCHAR2(50 BYTE), 
	"CRDT_DTM" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDT_BY" VARCHAR2(25 BYTE), 
	"UPDT_DTM" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEC_APP_RSRC
--------------------------------------------------------

  CREATE TABLE "BCDSS"."SEC_APP_RSRC" 
   (	"APP_RSRC_ID" NUMBER(38,0), 
	"APP_RSRC_NM" VARCHAR2(25 BYTE), 
	"APP_RSRC_DSCN" VARCHAR2(50 BYTE), 
	"CRDT_BY" VARCHAR2(50 BYTE), 
	"CRDT_DTM" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDT_BY" VARCHAR2(25 BYTE), 
	"UPDT_DTM" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEC_APP_RSRC_PERM
--------------------------------------------------------

  CREATE TABLE "BCDSS"."SEC_APP_RSRC_PERM" 
   (	"PERM_ID" NUMBER(38,0), 
	"APP_RSRC_ID" NUMBER(38,0), 
	"APP_RSRC_PERM" VARCHAR2(25 BYTE), 
	"CRDT_BY" VARCHAR2(50 BYTE), 
	"CRDT_DTM" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDT_BY" VARCHAR2(25 BYTE), 
	"UPDT_DTM" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEC_APP_USER
--------------------------------------------------------

  CREATE TABLE "BCDSS"."SEC_APP_USER" 
   (	"USER_ID" NUMBER(38,0), 
	"USER_NM" VARCHAR2(25 BYTE), 
	"USER_LOGIN" VARCHAR2(25 BYTE), 
	"USER_NTWK_ID" VARCHAR2(50 BYTE), 
	"PSWD" VARCHAR2(100 BYTE), 
	"STAS" VARCHAR2(25 BYTE), 
	"CRDT_BY" VARCHAR2(50 BYTE), 
	"CRDT_DTM" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDT_BY" VARCHAR2(50 BYTE), 
	"UPDT_DTM" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEC_APP_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "BCDSS"."SEC_APP_USER_ROLE" 
   (	"USER_ID" NUMBER(38,0), 
	"USER_ROLE_NM" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEC_PERM
--------------------------------------------------------

  CREATE TABLE "BCDSS"."SEC_PERM" 
   (	"PERM_ID" NUMBER(38,0), 
	"PERM_NM" VARCHAR2(25 BYTE), 
	"PERM_DSCN" VARCHAR2(100 BYTE), 
	"CRDT_BY" VARCHAR2(50 BYTE), 
	"CRDT_DTM" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDT_BY" VARCHAR2(25 BYTE), 
	"UPDT_DTM" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Materialized View MV_STGN_CLAIM
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BCDSS"."MV_STGN_CLAIM" ("VET_ID", "VET_NM", "REGN_OFfC", "CLAIM_ID", "DATE_OF_CLAIM", "CEST_DATE", "CNTNTN_CLMANT_TXT")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT
  PTCPNT_VET_ID AS "VET_ID",
  CONCAT('VETERAN ', TO_CHAR(PTCPNT_VET_ID)) AS "VET_NM",
  CLAIM_RO_NAME AS "REGN_OFfC",
  BNFT_CLAIM_ID AS "CLAIM_ID",
  DATE_OF_CLAIM,
  DATE_OF_CLAIM + 10 AS "CEST_DATE",
  CNTNTN_CLMANT_TXT
FROM
  DEVELOPER.AH4929_RATING_CORP_CLAIM 
WHERE CNTNTN_CLMANT_TXT LIKE '% KNEE %'
OR CNTNTN_CLMANT_TXT LIKE '% EAR %';
 

   COMMENT ON MATERIALIZED VIEW "BCDSS"."MV_STGN_CLAIM"  IS 'snapshot table for snapshot BCDSS.MV_STGN_CLAIM';
--------------------------------------------------------
--  DDL for Index DR$IX_RATING_CORP_CLAIM_03$R
--------------------------------------------------------

  CREATE INDEX "BCDSS"."DR$IX_RATING_CORP_CLAIM_03$R" ON "BCDSS"."DR$IX_RATING_CORP_CLAIM_03$I" ("DR$ROWID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DR$IX_RATING_CORP_CLAIM_03$X
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."DR$IX_RATING_CORP_CLAIM_03$X" ON "BCDSS"."DR$IX_RATING_CORP_CLAIM_03$I" ("DR$TOKEN", "DR$TOKEN_TYPE", "DR$ROWID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS 2 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_AUDIT_EVENT
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IDX_AUDIT_EVENT" ON "BCDSS"."AUDT_EVENT" ("PRINCIPAL", "EVENT_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_AUDIT_EVENT_DATA
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IDX_AUDIT_EVENT_DATA" ON "BCDSS"."AUDT_EVENT_DATA" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_CORP_CLAIM_01
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_CORP_CLAIM_01" ON "BCDSS"."AH4929_RATING_CORP_CLAIM" ("PTCPNT_VET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_CORP_CLAIM_03
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_CORP_CLAIM_03" ON "BCDSS"."AH4929_RATING_CORP_CLAIM" ("BNFT_CLAIM_TYPE_CD") 
   INDEXTYPE IS "CTXSYS"."CTXCAT" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_DECISION_01
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_DECISION_01" ON "BCDSS"."AH4929_RATING_DECISION_OLD" ("PTCPNT_VET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_DECISION_02
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_DECISION_02" ON "BCDSS"."AH4929_RATING_DECISION_OLD" ("PRFIL_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_DECISION_10
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_DECISION_10" ON "BCDSS"."AH4929_RATING_DECISION_OLD" ("SYSTEM_TYPE_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_DECISION_11
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_DECISION_11" ON "BCDSS"."AH4929_RATING_DECISION_OLD" ("BEGIN_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_DECISION_12
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_DECISION_12" ON "BCDSS"."AH4929_RATING_DECISION_OLD" ("END_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_DECISION_13
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_DECISION_13" ON "BCDSS"."AH4929_RATING_DECISION_OLD" ("DSBLTY_DECN_TYPE_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_DECISION_16
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_DECISION_16" ON "BCDSS"."AH4929_RATING_DECISION_OLD" ("PRMLGN_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_DECISION_19
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_DECISION_19" ON "BCDSS"."AH4929_RATING_DECISION_OLD" ("PREV_EVALTN_IND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_RATING_DECISION_20
--------------------------------------------------------

  CREATE INDEX "BCDSS"."IX_RATING_DECISION_20" ON "BCDSS"."AH4929_RATING_DECISION_OLD" ("DSBLTY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_AUDT_EVENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."PK_AUDT_EVENT" ON "BCDSS"."AUDT_EVENT" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_AUDT_PERSISTENT_TOKEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."PK_AUDT_PERSISTENT_TOKEN" ON "BCDSS"."AUDT_PERSISTENT_TOKEN" ("SERIES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DATABASECHANGELOGLOCK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."PK_DATABASECHANGELOGLOCK" ON "BCDSS"."DATABASECHANGELOGLOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REF1111
--------------------------------------------------------

  CREATE INDEX "BCDSS"."REF1111" ON "BCDSS"."SEC_APP_RSRC_PERM" ("APP_RSRC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REF88
--------------------------------------------------------

  CREATE INDEX "BCDSS"."REF88" ON "BCDSS"."SEC_APP_ROLE_PERM" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REF912
--------------------------------------------------------

  CREATE INDEX "BCDSS"."REF912" ON "BCDSS"."SEC_APP_RSRC_PERM" ("PERM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REF99
--------------------------------------------------------

  CREATE INDEX "BCDSS"."REF99" ON "BCDSS"."SEC_APP_ROLE_PERM" ("PERM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEC_ROLE_PK
--------------------------------------------------------

  CREATE INDEX "BCDSS"."SEC_ROLE_PK" ON "BCDSS"."SEC_APP_USER_ROLE" ("USER_ROLE_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEC_USER_PK
--------------------------------------------------------

  CREATE INDEX "BCDSS"."SEC_USER_PK" ON "BCDSS"."SEC_APP_USER_ROLE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010827
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010827" ON "BCDSS"."SEC_APP_ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010828
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010828" ON "BCDSS"."SEC_APP_ROLE" ("ROLE_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010829
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010829" ON "BCDSS"."SEC_APP_ROLE" ("ROLE_ID", "ROLE_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010835
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010835" ON "BCDSS"."SEC_PERM" ("PERM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010843
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010843" ON "BCDSS"."SEC_APP_USER" ("USER_LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010844
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010844" ON "BCDSS"."SEC_APP_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010853
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010853" ON "BCDSS"."SEC_APP_RSRC" ("APP_RSRC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010859
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010859" ON "BCDSS"."SEC_APP_ROLE_PERM" ("ROLE_ID", "PERM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010865
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010865" ON "BCDSS"."SEC_APP_RSRC_PERM" ("PERM_ID", "APP_RSRC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010880
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0010880" ON "BCDSS"."AUDT_EVENT_DATA" ("EVENT_ID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012705
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0012705" ON "BCDSS"."SEC_APP_USER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012730
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0012730" ON "BCDSS"."SEC_APP_USER_ROLE" ("USER_ID", "USER_ROLE_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018269
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."SYS_C0018269" ON "BCDSS"."BULK_PROCESS_REQUEST" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XIF1DDM_MODEL_CNTNT
--------------------------------------------------------

  CREATE INDEX "BCDSS"."XIF1DDM_MODEL_CNTNT" ON "BCDSS"."DDM_MODEL_CNTNT" ("PATTERN_ID", "MODEL_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XIF1DDM_MODEL_DIAG
--------------------------------------------------------

  CREATE INDEX "BCDSS"."XIF1DDM_MODEL_DIAG" ON "BCDSS"."DDM_MODEL_DIAG" ("PATTERN_ID", "MODEL_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XIF1DDM_MODEL_PATTERN_INDX
--------------------------------------------------------

  CREATE INDEX "BCDSS"."XIF1DDM_MODEL_PATTERN_INDX" ON "BCDSS"."DDM_MODEL_PATTERN_INDX" ("PATTERN_ID", "MODEL_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XIF2DDM_MODEL_CNTNT
--------------------------------------------------------

  CREATE INDEX "BCDSS"."XIF2DDM_MODEL_CNTNT" ON "BCDSS"."DDM_MODEL_CNTNT" ("CNTNT_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XIF2DDM_MODEL_DIAG
--------------------------------------------------------

  CREATE INDEX "BCDSS"."XIF2DDM_MODEL_DIAG" ON "BCDSS"."DDM_MODEL_DIAG" ("DIAG_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XIF2DDM_MODEL_PATTERN_INDX
--------------------------------------------------------

  CREATE INDEX "BCDSS"."XIF2DDM_MODEL_PATTERN_INDX" ON "BCDSS"."DDM_MODEL_PATTERN_INDX" ("CTLG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKDDM_CNTNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."XPKDDM_CNTNT" ON "BCDSS"."DDM_CNTNT" ("CNTNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKDDM_CTLG
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."XPKDDM_CTLG" ON "BCDSS"."DDM_CTLG" ("CTLG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKDDM_DIAG
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."XPKDDM_DIAG" ON "BCDSS"."DDM_DIAG" ("DIAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKDDM_MODELPATTERN
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."XPKDDM_MODELPATTERN" ON "BCDSS"."DDM_MODEL_PATTERN" ("PATTERN_ID", "MODEL_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKMODEL_RATING_RESULTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCDSS"."XPKMODEL_RATING_RESULTS" ON "BCDSS"."MODEL_RATING_RESULTS" ("PROCESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ndx_RATING_DECISION_01
--------------------------------------------------------

  CREATE INDEX "BCDSS"."ndx_RATING_DECISION_01" ON "BCDSS"."AH4929_RATING_DECISION" ("PTCPNT_VET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ndx_RATING_DECISION_02
--------------------------------------------------------

  CREATE INDEX "BCDSS"."ndx_RATING_DECISION_02" ON "BCDSS"."AH4929_RATING_DECISION" ("PRFIL_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ndx_RATING_DECISION_10
--------------------------------------------------------

  CREATE INDEX "BCDSS"."ndx_RATING_DECISION_10" ON "BCDSS"."AH4929_RATING_DECISION" ("SYSTEM_TYPE_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ndx_RATING_DECISION_11
--------------------------------------------------------

  CREATE INDEX "BCDSS"."ndx_RATING_DECISION_11" ON "BCDSS"."AH4929_RATING_DECISION" ("BEGIN_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ndx_RATING_DECISION_12
--------------------------------------------------------

  CREATE INDEX "BCDSS"."ndx_RATING_DECISION_12" ON "BCDSS"."AH4929_RATING_DECISION" ("END_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ndx_RATING_DECISION_13
--------------------------------------------------------

  CREATE INDEX "BCDSS"."ndx_RATING_DECISION_13" ON "BCDSS"."AH4929_RATING_DECISION" ("DSBLTY_DECN_TYPE_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ndx_RATING_DECISION_16
--------------------------------------------------------

  CREATE INDEX "BCDSS"."ndx_RATING_DECISION_16" ON "BCDSS"."AH4929_RATING_DECISION" ("PRMLGN_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ndx_RATING_DECISION_19
--------------------------------------------------------

  CREATE INDEX "BCDSS"."ndx_RATING_DECISION_19" ON "BCDSS"."AH4929_RATING_DECISION" ("PREV_EVALTN_IND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ndx_RATING_DECISION_20
--------------------------------------------------------

  CREATE INDEX "BCDSS"."ndx_RATING_DECISION_20" ON "BCDSS"."AH4929_RATING_DECISION" ("DSBLTY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AH4929_RATING_CORP_CLAIM
--------------------------------------------------------

  ALTER TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM" MODIFY ("PRFIL_DT" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM" MODIFY ("BNFT_CLAIM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM" MODIFY ("DATE_OF_CLAIM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM" MODIFY ("BNFT_CLAIM_TYPE_CD" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM" MODIFY ("CLAIM_LABEL" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM" MODIFY ("STATUS_TYPE_CD" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM" MODIFY ("CLAIM_RO_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_CORP_CLAIM" MODIFY ("CLAIM_RO_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AH4929_RATING_DECISION_OLD
--------------------------------------------------------

  ALTER TABLE "BCDSS"."AH4929_RATING_DECISION_OLD" MODIFY ("PTCPNT_VET_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_DECISION_OLD" MODIFY ("PRFIL_DT" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_DECISION_OLD" MODIFY ("STATION_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AH4929_RATING_DECISION_OLD" MODIFY ("STATION_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUDT_EVENT
--------------------------------------------------------

  ALTER TABLE "BCDSS"."AUDT_EVENT" ADD CONSTRAINT "PK_AUDT_EVENT" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BCDSS"."AUDT_EVENT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AUDT_EVENT" MODIFY ("PRINCIPAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUDT_EVENT_DATA
--------------------------------------------------------

  ALTER TABLE "BCDSS"."AUDT_EVENT_DATA" MODIFY ("EVENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AUDT_EVENT_DATA" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AUDT_EVENT_DATA" ADD PRIMARY KEY ("EVENT_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUDT_PERSISTENT_TOKEN
--------------------------------------------------------

  ALTER TABLE "BCDSS"."AUDT_PERSISTENT_TOKEN" ADD CONSTRAINT "PK_AUDT_PERSISTENT_TOKEN" PRIMARY KEY ("SERIES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BCDSS"."AUDT_PERSISTENT_TOKEN" MODIFY ("SERIES" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."AUDT_PERSISTENT_TOKEN" MODIFY ("TOKEN_VALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BULK_PROCESS_REQUEST
--------------------------------------------------------

  ALTER TABLE "BCDSS"."BULK_PROCESS_REQUEST" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."BULK_PROCESS_REQUEST" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."BULK_PROCESS_REQUEST" ADD PRIMARY KEY ("REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DATABASECHANGELOG
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DATABASECHANGELOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DATABASECHANGELOG" MODIFY ("AUTHOR" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DATABASECHANGELOG" MODIFY ("FILENAME" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DATABASECHANGELOG" MODIFY ("DATEEXECUTED" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DATABASECHANGELOG" MODIFY ("ORDEREXECUTED" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DATABASECHANGELOG" MODIFY ("EXECTYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATABASECHANGELOGLOCK
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DATABASECHANGELOGLOCK" ADD CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BCDSS"."DATABASECHANGELOGLOCK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DATABASECHANGELOGLOCK" MODIFY ("LOCKED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DDM_CNTNT
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DDM_CNTNT" MODIFY ("CNTNT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DDM_CNTNT" ADD CONSTRAINT "XPKDDM_CNTNT" PRIMARY KEY ("CNTNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DDM_CTLG
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DDM_CTLG" MODIFY ("CTLG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DDM_CTLG" ADD CONSTRAINT "XPKDDM_CTLG" PRIMARY KEY ("CTLG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DDM_DIAG
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DDM_DIAG" MODIFY ("DIAG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DDM_DIAG" MODIFY ("CTLG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DDM_DIAG" ADD CONSTRAINT "XPKDDM_DIAG" PRIMARY KEY ("DIAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DDM_MODEL_PATTERN
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DDM_MODEL_PATTERN" MODIFY ("PATTERN_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DDM_MODEL_PATTERN" MODIFY ("MODEL_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DDM_MODEL_PATTERN" ADD CONSTRAINT "XPKDDM_MODELPATTERN" PRIMARY KEY ("PATTERN_ID", "MODEL_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DR$IX_RATING_CORP_CLAIM_03$I
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DR$IX_RATING_CORP_CLAIM_03$I" MODIFY ("DR$TOKEN" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DR$IX_RATING_CORP_CLAIM_03$I" MODIFY ("DR$TOKEN_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DR$IX_RATING_CORP_CLAIM_03$I" MODIFY ("DR$ROWID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."DR$IX_RATING_CORP_CLAIM_03$I" MODIFY ("DR$TOKEN_INFO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MODEL_RATING_RESULTS
--------------------------------------------------------

  ALTER TABLE "BCDSS"."MODEL_RATING_RESULTS" MODIFY ("PROCESS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."MODEL_RATING_RESULTS" ADD CONSTRAINT "XPKMODEL_RATING_RESULTS" PRIMARY KEY ("PROCESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEC_APP_ROLE
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_APP_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE" MODIFY ("ROLE_NM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE" MODIFY ("ROLE_DSCN" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE" MODIFY ("CRDT_BY" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE" MODIFY ("CRDT_DTM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE" ADD UNIQUE ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE" ADD UNIQUE ("ROLE_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE" ADD PRIMARY KEY ("ROLE_ID", "ROLE_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEC_APP_ROLE_PERM
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_APP_ROLE_PERM" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE_PERM" MODIFY ("PERM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE_PERM" MODIFY ("ASSGN_PERM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE_PERM" MODIFY ("CRDT_BY" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE_PERM" MODIFY ("CRDT_DTM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE_PERM" ADD PRIMARY KEY ("ROLE_ID", "PERM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEC_APP_RSRC
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_APP_RSRC" MODIFY ("APP_RSRC_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC" MODIFY ("APP_RSRC_NM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC" MODIFY ("APP_RSRC_DSCN" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC" MODIFY ("CRDT_BY" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC" MODIFY ("CRDT_DTM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC" ADD PRIMARY KEY ("APP_RSRC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEC_APP_RSRC_PERM
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_APP_RSRC_PERM" MODIFY ("PERM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC_PERM" MODIFY ("APP_RSRC_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC_PERM" MODIFY ("APP_RSRC_PERM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC_PERM" MODIFY ("CRDT_BY" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC_PERM" MODIFY ("CRDT_DTM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC_PERM" ADD PRIMARY KEY ("PERM_ID", "APP_RSRC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEC_APP_USER
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_APP_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_USER" MODIFY ("USER_NM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_USER" MODIFY ("USER_LOGIN" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_USER" MODIFY ("PSWD" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_USER" MODIFY ("STAS" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_USER" MODIFY ("CRDT_BY" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_USER" MODIFY ("CRDT_DTM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_USER" ADD UNIQUE ("USER_LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BCDSS"."SEC_APP_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BCDSS"."SEC_APP_USER" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEC_APP_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_APP_USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_USER_ROLE" MODIFY ("USER_ROLE_NM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_APP_USER_ROLE" ADD PRIMARY KEY ("USER_ID", "USER_ROLE_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEC_PERM
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_PERM" MODIFY ("PERM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_PERM" MODIFY ("PERM_NM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_PERM" MODIFY ("PERM_DSCN" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_PERM" MODIFY ("CRDT_BY" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_PERM" MODIFY ("CRDT_DTM" NOT NULL ENABLE);
 
  ALTER TABLE "BCDSS"."SEC_PERM" ADD PRIMARY KEY ("PERM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUDT_EVENT_DATA
--------------------------------------------------------

  ALTER TABLE "BCDSS"."AUDT_EVENT_DATA" ADD CONSTRAINT "FK_EVT_PERS_AUDIT_EVT_DATA" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "BCDSS"."AUDT_EVENT" ("EVENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUDT_PERSISTENT_TOKEN
--------------------------------------------------------

  ALTER TABLE "BCDSS"."AUDT_PERSISTENT_TOKEN" ADD CONSTRAINT "FK_USER_PERSISTENT_TOKEN" FOREIGN KEY ("USER_ID")
	  REFERENCES "BCDSS"."SEC_APP_USER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DDM_CNTNT
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DDM_CNTNT" ADD CONSTRAINT "R_2" FOREIGN KEY ("CTLG_ID")
	  REFERENCES "BCDSS"."DDM_CTLG" ("CTLG_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DDM_DIAG
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DDM_DIAG" ADD CONSTRAINT "R_1" FOREIGN KEY ("CTLG_ID")
	  REFERENCES "BCDSS"."DDM_CTLG" ("CTLG_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DDM_MODEL_CNTNT
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DDM_MODEL_CNTNT" ADD CONSTRAINT "R_15" FOREIGN KEY ("PATTERN_ID", "MODEL_TYPE")
	  REFERENCES "BCDSS"."DDM_MODEL_PATTERN" ("PATTERN_ID", "MODEL_TYPE") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DDM_MODEL_DIAG
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DDM_MODEL_DIAG" ADD CONSTRAINT "R_14" FOREIGN KEY ("PATTERN_ID", "MODEL_TYPE")
	  REFERENCES "BCDSS"."DDM_MODEL_PATTERN" ("PATTERN_ID", "MODEL_TYPE") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DDM_MODEL_PATTERN_INDX
--------------------------------------------------------

  ALTER TABLE "BCDSS"."DDM_MODEL_PATTERN_INDX" ADD CONSTRAINT "R_4" FOREIGN KEY ("PATTERN_ID", "MODEL_TYPE")
	  REFERENCES "BCDSS"."DDM_MODEL_PATTERN" ("PATTERN_ID", "MODEL_TYPE") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODEL_RATING_RESULTS_CNTNT
--------------------------------------------------------

  ALTER TABLE "BCDSS"."MODEL_RATING_RESULTS_CNTNT" ADD CONSTRAINT "R_12" FOREIGN KEY ("PROCESS_ID")
	  REFERENCES "BCDSS"."MODEL_RATING_RESULTS" ("PROCESS_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODEL_RATING_RESULTS_DIAG
--------------------------------------------------------

  ALTER TABLE "BCDSS"."MODEL_RATING_RESULTS_DIAG" ADD CONSTRAINT "R_11" FOREIGN KEY ("PROCESS_ID")
	  REFERENCES "BCDSS"."MODEL_RATING_RESULTS" ("PROCESS_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODEL_RATING_RESULTS_STATUS
--------------------------------------------------------

  ALTER TABLE "BCDSS"."MODEL_RATING_RESULTS_STATUS" ADD CONSTRAINT "R_13" FOREIGN KEY ("PROCESS_ID")
	  REFERENCES "BCDSS"."MODEL_RATING_RESULTS" ("PROCESS_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEC_APP_ROLE_PERM
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_APP_ROLE_PERM" ADD CONSTRAINT "REFSEC_APP_ROLE8" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "BCDSS"."SEC_APP_ROLE" ("ROLE_ID") ENABLE;
 
  ALTER TABLE "BCDSS"."SEC_APP_ROLE_PERM" ADD CONSTRAINT "REFSEC_PERM9" FOREIGN KEY ("PERM_ID")
	  REFERENCES "BCDSS"."SEC_PERM" ("PERM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEC_APP_RSRC_PERM
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_APP_RSRC_PERM" ADD CONSTRAINT "REFSEC_APP_RSRC11" FOREIGN KEY ("APP_RSRC_ID")
	  REFERENCES "BCDSS"."SEC_APP_RSRC" ("APP_RSRC_ID") ENABLE;
 
  ALTER TABLE "BCDSS"."SEC_APP_RSRC_PERM" ADD CONSTRAINT "REFSEC_PERM12" FOREIGN KEY ("PERM_ID")
	  REFERENCES "BCDSS"."SEC_PERM" ("PERM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEC_APP_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "BCDSS"."SEC_APP_USER_ROLE" ADD CONSTRAINT "REFSEC_APP_ROLE6" FOREIGN KEY ("USER_ID")
	  REFERENCES "BCDSS"."SEC_APP_USER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger DDM_CNTNT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BCDSS"."DDM_CNTNT_TRG" 
BEFORE INSERT ON DDM_CNTNT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CNTNT_ID IS NULL THEN
      SELECT DDM_CNTNT_SEQ.NEXTVAL INTO :NEW.CNTNT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BCDSS"."DDM_CNTNT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DDM_DIAG_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BCDSS"."DDM_DIAG_TRG" 
BEFORE INSERT ON DDM_DIAG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.DIAG_ID IS NULL THEN
      SELECT DDM_DIAG_SEQ.NEXTVAL INTO :NEW.DIAG_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BCDSS"."DDM_DIAG_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DDM_MODEL_PATTERN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BCDSS"."DDM_MODEL_PATTERN_TRG" 
BEFORE INSERT ON BCDSS.DDM_MODEL_PATTERN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BCDSS"."DDM_MODEL_PATTERN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DR$IX_RATING_CORP_CLAIM_03TC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BCDSS"."DR$IX_RATING_CORP_CLAIM_03TC" after insert or update on "BCDSS"."AH4929_RATING_CORP_CLAIM" for each row declare   reindex boolean := FALSE;   updop   boolean := FALSE; begin   ctxsys.drvdml.c_updtab.delete;   ctxsys.drvdml.c_numtab.delete;   ctxsys.drvdml.c_vctab.delete;   ctxsys.drvdml.c_rowid := :new.rowid;   if (inserting or updating('BNFT_CLAIM_TYPE_CD') or       :new."BNFT_CLAIM_TYPE_CD" <> :old."BNFT_CLAIM_TYPE_CD") then     reindex := TRUE;     updop := (not inserting);     ctxsys.drvdml.c_text_vc2 := :new."BNFT_CLAIM_TYPE_CD";   end if;   ctxsys.drvdml.ctxcat_dml('BCDSS','IX_RATING_CORP_CLAIM_03', reindex, updop); end;
/
ALTER TRIGGER "BCDSS"."DR$IX_RATING_CORP_CLAIM_03TC" ENABLE;
BEGIN 
  DBMS_DDL.SET_TRIGGER_FIRING_PROPERTY('"BCDSS"','"DR$IX_RATING_CORP_CLAIM_03TC"',FALSE) ; 
END;

/
