server:
    port: 8181

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    datasource:
        driverClassName: oracle.jdbc.OracleDriver
        dataSourceClassName: oracle.jdbc.pool.OracleDataSource
#        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
#        url: jdbc:mysql://localhost:3306/bcds?useUnicode=true&characterEncoding=utf8
        url: jdbc:oracle:thin:@bcdsdb:1521/DEV
        databaseName:
        serverName:
        username: SYS as sysdba
        password: D3vVV0Rd
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
#        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database-platform: org.hibernate.dialect.Oracle10gDialect
        database: ORACLE
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            hibernate.id.new_generator_mappings: true
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: bcds

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

spring.jpa.properties.org.hibernate.envers.audit_table_prefix: AUDIT_
spring.jpa.properties.org.hibernate.envers.audit_table_suffix:
spring.jpa.properties.org.hibernate.envers.default_schema: BCDS
spring.jpa.properties.org.hibernate.envers.do_not_audit_optimistic_locking_field: true

