package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Ah4929RatingCorpClaim generated by hbm2java
 */
public class Ah4929RatingCorpClaim implements java.io.Serializable {

	private Ah4929RatingCorpClaimId id;

	public Ah4929RatingCorpClaim() {
	}

	public Ah4929RatingCorpClaim(Ah4929RatingCorpClaimId id) {
		this.id = id;
	}

	public Ah4929RatingCorpClaimId getId() {
		return this.id;
	}

	public void setId(Ah4929RatingCorpClaimId id) {
		this.id = id;
	}

}
