package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * AudtEventData generated by hbm2java
 */
public class AudtEventData implements java.io.Serializable {

	private AudtEventDataId id;
	private AudtEvent audtEvent;
	private String value;

	public AudtEventData() {
	}

	public AudtEventData(AudtEventDataId id, AudtEvent audtEvent) {
		this.id = id;
		this.audtEvent = audtEvent;
	}

	public AudtEventData(AudtEventDataId id, AudtEvent audtEvent, String value) {
		this.id = id;
		this.audtEvent = audtEvent;
		this.value = value;
	}

	public AudtEventDataId getId() {
		return this.id;
	}

	public void setId(AudtEventDataId id) {
		this.id = id;
	}

	public AudtEvent getAudtEvent() {
		return this.audtEvent;
	}

	public void setAudtEvent(AudtEvent audtEvent) {
		this.audtEvent = audtEvent;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
