package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;

/**
 * Databasechangeloglock generated by hbm2java
 */
public class Databasechangeloglock implements java.io.Serializable {

	private long id;
	private boolean locked;
	private Serializable lockgranted;
	private String lockedby;

	public Databasechangeloglock() {
	}

	public Databasechangeloglock(long id, boolean locked) {
		this.id = id;
		this.locked = locked;
	}

	public Databasechangeloglock(long id, boolean locked, Serializable lockgranted, String lockedby) {
		this.id = id;
		this.locked = locked;
		this.lockgranted = lockgranted;
		this.lockedby = lockedby;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public boolean isLocked() {
		return this.locked;
	}

	public void setLocked(boolean locked) {
		this.locked = locked;
	}

	public Serializable getLockgranted() {
		return this.lockgranted;
	}

	public void setLockgranted(Serializable lockgranted) {
		this.lockgranted = lockgranted;
	}

	public String getLockedby() {
		return this.lockedby;
	}

	public void setLockedby(String lockedby) {
		this.lockedby = lockedby;
	}

}
