package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Databasechangelog generated by hbm2java
 */
public class Databasechangelog implements java.io.Serializable {

	private DatabasechangelogId id;

	public Databasechangelog() {
	}

	public Databasechangelog(DatabasechangelogId id) {
		this.id = id;
	}

	public DatabasechangelogId getId() {
		return this.id;
	}

	public void setId(DatabasechangelogId id) {
		this.id = id;
	}

}
