package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DdmDiag generated by hbm2java
 */
public class DdmDiag implements java.io.Serializable {

	private BigDecimal diagId;
	private DdmCtlg ddmCtlg;
	private BigDecimal diagCd;
	private String diagCdDesc;
	private String crtdBy;
	private Date crtdDtm;
	private String modelType;
	private Set ddmModelDiags = new HashSet(0);
	private Set modelRatingResultsDiags = new HashSet(0);

	public DdmDiag() {
	}

	public DdmDiag(BigDecimal diagId, DdmCtlg ddmCtlg) {
		this.diagId = diagId;
		this.ddmCtlg = ddmCtlg;
	}

	public DdmDiag(BigDecimal diagId, DdmCtlg ddmCtlg, BigDecimal diagCd, String diagCdDesc, String crtdBy,
			Date crtdDtm, String modelType, Set ddmModelDiags, Set modelRatingResultsDiags) {
		this.diagId = diagId;
		this.ddmCtlg = ddmCtlg;
		this.diagCd = diagCd;
		this.diagCdDesc = diagCdDesc;
		this.crtdBy = crtdBy;
		this.crtdDtm = crtdDtm;
		this.modelType = modelType;
		this.ddmModelDiags = ddmModelDiags;
		this.modelRatingResultsDiags = modelRatingResultsDiags;
	}

	public BigDecimal getDiagId() {
		return this.diagId;
	}

	public void setDiagId(BigDecimal diagId) {
		this.diagId = diagId;
	}

	public DdmCtlg getDdmCtlg() {
		return this.ddmCtlg;
	}

	public void setDdmCtlg(DdmCtlg ddmCtlg) {
		this.ddmCtlg = ddmCtlg;
	}

	public BigDecimal getDiagCd() {
		return this.diagCd;
	}

	public void setDiagCd(BigDecimal diagCd) {
		this.diagCd = diagCd;
	}

	public String getDiagCdDesc() {
		return this.diagCdDesc;
	}

	public void setDiagCdDesc(String diagCdDesc) {
		this.diagCdDesc = diagCdDesc;
	}

	public String getCrtdBy() {
		return this.crtdBy;
	}

	public void setCrtdBy(String crtdBy) {
		this.crtdBy = crtdBy;
	}

	public Date getCrtdDtm() {
		return this.crtdDtm;
	}

	public void setCrtdDtm(Date crtdDtm) {
		this.crtdDtm = crtdDtm;
	}

	public String getModelType() {
		return this.modelType;
	}

	public void setModelType(String modelType) {
		this.modelType = modelType;
	}

	public Set getDdmModelDiags() {
		return this.ddmModelDiags;
	}

	public void setDdmModelDiags(Set ddmModelDiags) {
		this.ddmModelDiags = ddmModelDiags;
	}

	public Set getModelRatingResultsDiags() {
		return this.modelRatingResultsDiags;
	}

	public void setModelRatingResultsDiags(Set modelRatingResultsDiags) {
		this.modelRatingResultsDiags = modelRatingResultsDiags;
	}

}
