package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DdmModelPattern generated by hbm2java
 */
public class DdmModelPattern implements java.io.Serializable {

	private DdmModelPatternId id;
	private BigDecimal claimantAge;
	private BigDecimal claimCount;
	private BigDecimal contentionCount;
	private BigDecimal priorCdd;
	private BigDecimal cddAge;
	private Set ddmModelDiags = new HashSet(0);
	private Set ddmModelPatternIndxes = new HashSet(0);
	private Set ddmModelCntnts = new HashSet(0);

	public DdmModelPattern() {
	}

	public DdmModelPattern(DdmModelPatternId id) {
		this.id = id;
	}

	public DdmModelPattern(DdmModelPatternId id, BigDecimal claimantAge, BigDecimal claimCount,
			BigDecimal contentionCount, BigDecimal priorCdd, BigDecimal cddAge, Set ddmModelDiags,
			Set ddmModelPatternIndxes, Set ddmModelCntnts) {
		this.id = id;
		this.claimantAge = claimantAge;
		this.claimCount = claimCount;
		this.contentionCount = contentionCount;
		this.priorCdd = priorCdd;
		this.cddAge = cddAge;
		this.ddmModelDiags = ddmModelDiags;
		this.ddmModelPatternIndxes = ddmModelPatternIndxes;
		this.ddmModelCntnts = ddmModelCntnts;
	}

	public DdmModelPatternId getId() {
		return this.id;
	}

	public void setId(DdmModelPatternId id) {
		this.id = id;
	}

	public BigDecimal getClaimantAge() {
		return this.claimantAge;
	}

	public void setClaimantAge(BigDecimal claimantAge) {
		this.claimantAge = claimantAge;
	}

	public BigDecimal getClaimCount() {
		return this.claimCount;
	}

	public void setClaimCount(BigDecimal claimCount) {
		this.claimCount = claimCount;
	}

	public BigDecimal getContentionCount() {
		return this.contentionCount;
	}

	public void setContentionCount(BigDecimal contentionCount) {
		this.contentionCount = contentionCount;
	}

	public BigDecimal getPriorCdd() {
		return this.priorCdd;
	}

	public void setPriorCdd(BigDecimal priorCdd) {
		this.priorCdd = priorCdd;
	}

	public BigDecimal getCddAge() {
		return this.cddAge;
	}

	public void setCddAge(BigDecimal cddAge) {
		this.cddAge = cddAge;
	}

	public Set getDdmModelDiags() {
		return this.ddmModelDiags;
	}

	public void setDdmModelDiags(Set ddmModelDiags) {
		this.ddmModelDiags = ddmModelDiags;
	}

	public Set getDdmModelPatternIndxes() {
		return this.ddmModelPatternIndxes;
	}

	public void setDdmModelPatternIndxes(Set ddmModelPatternIndxes) {
		this.ddmModelPatternIndxes = ddmModelPatternIndxes;
	}

	public Set getDdmModelCntnts() {
		return this.ddmModelCntnts;
	}

	public void setDdmModelCntnts(Set ddmModelCntnts) {
		this.ddmModelCntnts = ddmModelCntnts;
	}

}
