package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;

/**
 * DdmModelPatternIndxId generated by hbm2java
 */
public class DdmModelPatternIndxId implements java.io.Serializable {

	private BigDecimal patternId;
	private BigDecimal accuracy;
	private BigDecimal cdd;
	private BigDecimal patternIndxNumber;
	private String crtdBy;
	private Date crtdDtm;
	private BigDecimal ctlgId;
	private String modelType;

	public DdmModelPatternIndxId() {
	}

	public DdmModelPatternIndxId(BigDecimal patternId, BigDecimal accuracy, BigDecimal cdd,
			BigDecimal patternIndxNumber, String crtdBy, Date crtdDtm, BigDecimal ctlgId, String modelType) {
		this.patternId = patternId;
		this.accuracy = accuracy;
		this.cdd = cdd;
		this.patternIndxNumber = patternIndxNumber;
		this.crtdBy = crtdBy;
		this.crtdDtm = crtdDtm;
		this.ctlgId = ctlgId;
		this.modelType = modelType;
	}

	public BigDecimal getPatternId() {
		return this.patternId;
	}

	public void setPatternId(BigDecimal patternId) {
		this.patternId = patternId;
	}

	public BigDecimal getAccuracy() {
		return this.accuracy;
	}

	public void setAccuracy(BigDecimal accuracy) {
		this.accuracy = accuracy;
	}

	public BigDecimal getCdd() {
		return this.cdd;
	}

	public void setCdd(BigDecimal cdd) {
		this.cdd = cdd;
	}

	public BigDecimal getPatternIndxNumber() {
		return this.patternIndxNumber;
	}

	public void setPatternIndxNumber(BigDecimal patternIndxNumber) {
		this.patternIndxNumber = patternIndxNumber;
	}

	public String getCrtdBy() {
		return this.crtdBy;
	}

	public void setCrtdBy(String crtdBy) {
		this.crtdBy = crtdBy;
	}

	public Date getCrtdDtm() {
		return this.crtdDtm;
	}

	public void setCrtdDtm(Date crtdDtm) {
		this.crtdDtm = crtdDtm;
	}

	public BigDecimal getCtlgId() {
		return this.ctlgId;
	}

	public void setCtlgId(BigDecimal ctlgId) {
		this.ctlgId = ctlgId;
	}

	public String getModelType() {
		return this.modelType;
	}

	public void setModelType(String modelType) {
		this.modelType = modelType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DdmModelPatternIndxId))
			return false;
		DdmModelPatternIndxId castOther = (DdmModelPatternIndxId) other;

		return ((this.getPatternId() == castOther.getPatternId()) || (this.getPatternId() != null
				&& castOther.getPatternId() != null && this.getPatternId().equals(castOther.getPatternId())))
				&& ((this.getAccuracy() == castOther.getAccuracy()) || (this.getAccuracy() != null
						&& castOther.getAccuracy() != null && this.getAccuracy().equals(castOther.getAccuracy())))
				&& ((this.getCdd() == castOther.getCdd()) || (this.getCdd() != null && castOther.getCdd() != null
						&& this.getCdd().equals(castOther.getCdd())))
				&& ((this.getPatternIndxNumber() == castOther.getPatternIndxNumber())
						|| (this.getPatternIndxNumber() != null && castOther.getPatternIndxNumber() != null
								&& this.getPatternIndxNumber().equals(castOther.getPatternIndxNumber())))
				&& ((this.getCrtdBy() == castOther.getCrtdBy()) || (this.getCrtdBy() != null
						&& castOther.getCrtdBy() != null && this.getCrtdBy().equals(castOther.getCrtdBy())))
				&& ((this.getCrtdDtm() == castOther.getCrtdDtm()) || (this.getCrtdDtm() != null
						&& castOther.getCrtdDtm() != null && this.getCrtdDtm().equals(castOther.getCrtdDtm())))
				&& ((this.getCtlgId() == castOther.getCtlgId()) || (this.getCtlgId() != null
						&& castOther.getCtlgId() != null && this.getCtlgId().equals(castOther.getCtlgId())))
				&& ((this.getModelType() == castOther.getModelType()) || (this.getModelType() != null
						&& castOther.getModelType() != null && this.getModelType().equals(castOther.getModelType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPatternId() == null ? 0 : this.getPatternId().hashCode());
		result = 37 * result + (getAccuracy() == null ? 0 : this.getAccuracy().hashCode());
		result = 37 * result + (getCdd() == null ? 0 : this.getCdd().hashCode());
		result = 37 * result + (getPatternIndxNumber() == null ? 0 : this.getPatternIndxNumber().hashCode());
		result = 37 * result + (getCrtdBy() == null ? 0 : this.getCrtdBy().hashCode());
		result = 37 * result + (getCrtdDtm() == null ? 0 : this.getCrtdDtm().hashCode());
		result = 37 * result + (getCtlgId() == null ? 0 : this.getCtlgId().hashCode());
		result = 37 * result + (getModelType() == null ? 0 : this.getModelType().hashCode());
		return result;
	}

}
