package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

/**
 * DdmModelDiagId generated by hbm2java
 */
public class DdmModelDiagId implements java.io.Serializable {

	private BigDecimal patternId;
	private BigDecimal diagId;
	private BigDecimal count;
	private String modelType;

	public DdmModelDiagId() {
	}

	public DdmModelDiagId(BigDecimal patternId, BigDecimal diagId, BigDecimal count, String modelType) {
		this.patternId = patternId;
		this.diagId = diagId;
		this.count = count;
		this.modelType = modelType;
	}

	public BigDecimal getPatternId() {
		return this.patternId;
	}

	public void setPatternId(BigDecimal patternId) {
		this.patternId = patternId;
	}

	public BigDecimal getDiagId() {
		return this.diagId;
	}

	public void setDiagId(BigDecimal diagId) {
		this.diagId = diagId;
	}

	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	public String getModelType() {
		return this.modelType;
	}

	public void setModelType(String modelType) {
		this.modelType = modelType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DdmModelDiagId))
			return false;
		DdmModelDiagId castOther = (DdmModelDiagId) other;

		return ((this.getPatternId() == castOther.getPatternId()) || (this.getPatternId() != null
				&& castOther.getPatternId() != null && this.getPatternId().equals(castOther.getPatternId())))
				&& ((this.getDiagId() == castOther.getDiagId()) || (this.getDiagId() != null
						&& castOther.getDiagId() != null && this.getDiagId().equals(castOther.getDiagId())))
				&& ((this.getCount() == castOther.getCount()) || (this.getCount() != null
						&& castOther.getCount() != null && this.getCount().equals(castOther.getCount())))
				&& ((this.getModelType() == castOther.getModelType()) || (this.getModelType() != null
						&& castOther.getModelType() != null && this.getModelType().equals(castOther.getModelType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPatternId() == null ? 0 : this.getPatternId().hashCode());
		result = 37 * result + (getDiagId() == null ? 0 : this.getDiagId().hashCode());
		result = 37 * result + (getCount() == null ? 0 : this.getCount().hashCode());
		result = 37 * result + (getModelType() == null ? 0 : this.getModelType().hashCode());
		return result;
	}

}
