package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * ModelRatingResultsDiag generated by hbm2java
 */
public class ModelRatingResultsDiag implements java.io.Serializable {

	private ModelRatingResultsDiagId id;
	private DdmDiag ddmDiag;
	private ModelRatingResults modelRatingResults;

	public ModelRatingResultsDiag() {
	}

	public ModelRatingResultsDiag(ModelRatingResultsDiagId id) {
		this.id = id;
	}

	public ModelRatingResultsDiag(ModelRatingResultsDiagId id, DdmDiag ddmDiag, ModelRatingResults modelRatingResults) {
		this.id = id;
		this.ddmDiag = ddmDiag;
		this.modelRatingResults = modelRatingResults;
	}

	public ModelRatingResultsDiagId getId() {
		return this.id;
	}

	public void setId(ModelRatingResultsDiagId id) {
		this.id = id;
	}

	public DdmDiag getDdmDiag() {
		return this.ddmDiag;
	}

	public void setDdmDiag(DdmDiag ddmDiag) {
		this.ddmDiag = ddmDiag;
	}

	public ModelRatingResults getModelRatingResults() {
		return this.modelRatingResults;
	}

	public void setModelRatingResults(ModelRatingResults modelRatingResults) {
		this.modelRatingResults = modelRatingResults;
	}

}
