package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * ModelRatingResultsStatus generated by hbm2java
 */
public class ModelRatingResultsStatus implements java.io.Serializable {

	private ModelRatingResultsStatusId id;
	private ModelRatingResults modelRatingResults;

	public ModelRatingResultsStatus() {
	}

	public ModelRatingResultsStatus(ModelRatingResultsStatusId id) {
		this.id = id;
	}

	public ModelRatingResultsStatus(ModelRatingResultsStatusId id, ModelRatingResults modelRatingResults) {
		this.id = id;
		this.modelRatingResults = modelRatingResults;
	}

	public ModelRatingResultsStatusId getId() {
		return this.id;
	}

	public void setId(ModelRatingResultsStatusId id) {
		this.id = id;
	}

	public ModelRatingResults getModelRatingResults() {
		return this.modelRatingResults;
	}

	public void setModelRatingResults(ModelRatingResults modelRatingResults) {
		this.modelRatingResults = modelRatingResults;
	}

}
