package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

/**
 * ModelRatingResultsDiagId generated by hbm2java
 */
public class ModelRatingResultsDiagId implements java.io.Serializable {

	private BigDecimal diagId;
	private BigDecimal processId;
	private BigDecimal count;

	public ModelRatingResultsDiagId() {
	}

	public ModelRatingResultsDiagId(BigDecimal diagId, BigDecimal processId, BigDecimal count) {
		this.diagId = diagId;
		this.processId = processId;
		this.count = count;
	}

	public BigDecimal getDiagId() {
		return this.diagId;
	}

	public void setDiagId(BigDecimal diagId) {
		this.diagId = diagId;
	}

	public BigDecimal getProcessId() {
		return this.processId;
	}

	public void setProcessId(BigDecimal processId) {
		this.processId = processId;
	}

	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelRatingResultsDiagId))
			return false;
		ModelRatingResultsDiagId castOther = (ModelRatingResultsDiagId) other;

		return ((this.getDiagId() == castOther.getDiagId()) || (this.getDiagId() != null
				&& castOther.getDiagId() != null && this.getDiagId().equals(castOther.getDiagId())))
				&& ((this.getProcessId() == castOther.getProcessId()) || (this.getProcessId() != null
						&& castOther.getProcessId() != null && this.getProcessId().equals(castOther.getProcessId())))
				&& ((this.getCount() == castOther.getCount()) || (this.getCount() != null
						&& castOther.getCount() != null && this.getCount().equals(castOther.getCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDiagId() == null ? 0 : this.getDiagId().hashCode());
		result = 37 * result + (getProcessId() == null ? 0 : this.getProcessId().hashCode());
		result = 37 * result + (getCount() == null ? 0 : this.getCount().hashCode());
		return result;
	}

}
