package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * MvStgnClaimId generated by hbm2java
 */
public class MvStgnClaimId implements java.io.Serializable {

	private Long vetId;
	private String vetNm;
	private String regnOffC;
	private long claimId;
	private Date dateOfClaim;
	private Date cestDate;
	private String cntntnClmantTxt;

	public MvStgnClaimId() {
	}

	public MvStgnClaimId(String regnOffC, long claimId, Date dateOfClaim) {
		this.regnOffC = regnOffC;
		this.claimId = claimId;
		this.dateOfClaim = dateOfClaim;
	}

	public MvStgnClaimId(Long vetId, String vetNm, String regnOffC, long claimId, Date dateOfClaim, Date cestDate,
			String cntntnClmantTxt) {
		this.vetId = vetId;
		this.vetNm = vetNm;
		this.regnOffC = regnOffC;
		this.claimId = claimId;
		this.dateOfClaim = dateOfClaim;
		this.cestDate = cestDate;
		this.cntntnClmantTxt = cntntnClmantTxt;
	}

	public Long getVetId() {
		return this.vetId;
	}

	public void setVetId(Long vetId) {
		this.vetId = vetId;
	}

	public String getVetNm() {
		return this.vetNm;
	}

	public void setVetNm(String vetNm) {
		this.vetNm = vetNm;
	}

	public String getRegnOffC() {
		return this.regnOffC;
	}

	public void setRegnOffC(String regnOffC) {
		this.regnOffC = regnOffC;
	}

	public long getClaimId() {
		return this.claimId;
	}

	public void setClaimId(long claimId) {
		this.claimId = claimId;
	}

	public Date getDateOfClaim() {
		return this.dateOfClaim;
	}

	public void setDateOfClaim(Date dateOfClaim) {
		this.dateOfClaim = dateOfClaim;
	}

	public Date getCestDate() {
		return this.cestDate;
	}

	public void setCestDate(Date cestDate) {
		this.cestDate = cestDate;
	}

	public String getCntntnClmantTxt() {
		return this.cntntnClmantTxt;
	}

	public void setCntntnClmantTxt(String cntntnClmantTxt) {
		this.cntntnClmantTxt = cntntnClmantTxt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MvStgnClaimId))
			return false;
		MvStgnClaimId castOther = (MvStgnClaimId) other;

		return ((this.getVetId() == castOther.getVetId()) || (this.getVetId() != null && castOther.getVetId() != null
				&& this.getVetId().equals(castOther.getVetId())))
				&& ((this.getVetNm() == castOther.getVetNm()) || (this.getVetNm() != null
						&& castOther.getVetNm() != null && this.getVetNm().equals(castOther.getVetNm())))
				&& ((this.getRegnOffC() == castOther.getRegnOffC()) || (this.getRegnOffC() != null
						&& castOther.getRegnOffC() != null && this.getRegnOffC().equals(castOther.getRegnOffC())))
				&& (this.getClaimId() == castOther.getClaimId())
				&& ((this.getDateOfClaim() == castOther.getDateOfClaim())
						|| (this.getDateOfClaim() != null && castOther.getDateOfClaim() != null
								&& this.getDateOfClaim().equals(castOther.getDateOfClaim())))
				&& ((this.getCestDate() == castOther.getCestDate()) || (this.getCestDate() != null
						&& castOther.getCestDate() != null && this.getCestDate().equals(castOther.getCestDate())))
				&& ((this.getCntntnClmantTxt() == castOther.getCntntnClmantTxt())
						|| (this.getCntntnClmantTxt() != null && castOther.getCntntnClmantTxt() != null
								&& this.getCntntnClmantTxt().equals(castOther.getCntntnClmantTxt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getVetId() == null ? 0 : this.getVetId().hashCode());
		result = 37 * result + (getVetNm() == null ? 0 : this.getVetNm().hashCode());
		result = 37 * result + (getRegnOffC() == null ? 0 : this.getRegnOffC().hashCode());
		result = 37 * result + (int) this.getClaimId();
		result = 37 * result + (getDateOfClaim() == null ? 0 : this.getDateOfClaim().hashCode());
		result = 37 * result + (getCestDate() == null ? 0 : this.getCestDate().hashCode());
		result = 37 * result + (getCntntnClmantTxt() == null ? 0 : this.getCntntnClmantTxt().hashCode());
		return result;
	}

}
