package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

/**
 * SecAppRoleId generated by hbm2java
 */
public class SecAppRoleId implements java.io.Serializable {

	private BigDecimal roleId;
	private String roleNm;

	public SecAppRoleId() {
	}

	public SecAppRoleId(BigDecimal roleId, String roleNm) {
		this.roleId = roleId;
		this.roleNm = roleNm;
	}

	public BigDecimal getRoleId() {
		return this.roleId;
	}

	public void setRoleId(BigDecimal roleId) {
		this.roleId = roleId;
	}

	public String getRoleNm() {
		return this.roleNm;
	}

	public void setRoleNm(String roleNm) {
		this.roleNm = roleNm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SecAppRoleId))
			return false;
		SecAppRoleId castOther = (SecAppRoleId) other;

		return ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
				&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getRoleNm() == castOther.getRoleNm()) || (this.getRoleNm() != null
						&& castOther.getRoleNm() != null && this.getRoleNm().equals(castOther.getRoleNm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getRoleNm() == null ? 0 : this.getRoleNm().hashCode());
		return result;
	}

}
