package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;

/**
 * SecAppRolePerm generated by hbm2java
 */
public class SecAppRolePerm implements java.io.Serializable {

	private SecAppRolePermId id;
	private SecPerm secPerm;
	private String assgnPerm;
	private String crdtBy;
	private Serializable crdtDtm;
	private String updtBy;
	private Serializable updtDtm;

	public SecAppRolePerm() {
	}

	public SecAppRolePerm(SecAppRolePermId id, SecPerm secPerm, String assgnPerm, String crdtBy, Serializable crdtDtm) {
		this.id = id;
		this.secPerm = secPerm;
		this.assgnPerm = assgnPerm;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
	}

	public SecAppRolePerm(SecAppRolePermId id, SecPerm secPerm, String assgnPerm, String crdtBy, Serializable crdtDtm,
			String updtBy, Serializable updtDtm) {
		this.id = id;
		this.secPerm = secPerm;
		this.assgnPerm = assgnPerm;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
		this.updtBy = updtBy;
		this.updtDtm = updtDtm;
	}

	public SecAppRolePermId getId() {
		return this.id;
	}

	public void setId(SecAppRolePermId id) {
		this.id = id;
	}

	public SecPerm getSecPerm() {
		return this.secPerm;
	}

	public void setSecPerm(SecPerm secPerm) {
		this.secPerm = secPerm;
	}

	public String getAssgnPerm() {
		return this.assgnPerm;
	}

	public void setAssgnPerm(String assgnPerm) {
		this.assgnPerm = assgnPerm;
	}

	public String getCrdtBy() {
		return this.crdtBy;
	}

	public void setCrdtBy(String crdtBy) {
		this.crdtBy = crdtBy;
	}

	public Serializable getCrdtDtm() {
		return this.crdtDtm;
	}

	public void setCrdtDtm(Serializable crdtDtm) {
		this.crdtDtm = crdtDtm;
	}

	public String getUpdtBy() {
		return this.updtBy;
	}

	public void setUpdtBy(String updtBy) {
		this.updtBy = updtBy;
	}

	public Serializable getUpdtDtm() {
		return this.updtDtm;
	}

	public void setUpdtDtm(Serializable updtDtm) {
		this.updtDtm = updtDtm;
	}

}
