package gov.va.vba.bcdss.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SecPerm generated by hbm2java
 */
public class SecPerm implements java.io.Serializable {

	private BigDecimal permId;
	private String permNm;
	private String permDscn;
	private String crdtBy;
	private Serializable crdtDtm;
	private String updtBy;
	private Serializable updtDtm;
	private Set secAppRsrcPerms = new HashSet(0);
	private Set secAppRolePerms = new HashSet(0);

	public SecPerm() {
	}

	public SecPerm(BigDecimal permId, String permNm, String permDscn, String crdtBy, Serializable crdtDtm) {
		this.permId = permId;
		this.permNm = permNm;
		this.permDscn = permDscn;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
	}

	public SecPerm(BigDecimal permId, String permNm, String permDscn, String crdtBy, Serializable crdtDtm,
			String updtBy, Serializable updtDtm, Set secAppRsrcPerms, Set secAppRolePerms) {
		this.permId = permId;
		this.permNm = permNm;
		this.permDscn = permDscn;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
		this.updtBy = updtBy;
		this.updtDtm = updtDtm;
		this.secAppRsrcPerms = secAppRsrcPerms;
		this.secAppRolePerms = secAppRolePerms;
	}

	public BigDecimal getPermId() {
		return this.permId;
	}

	public void setPermId(BigDecimal permId) {
		this.permId = permId;
	}

	public String getPermNm() {
		return this.permNm;
	}

	public void setPermNm(String permNm) {
		this.permNm = permNm;
	}

	public String getPermDscn() {
		return this.permDscn;
	}

	public void setPermDscn(String permDscn) {
		this.permDscn = permDscn;
	}

	public String getCrdtBy() {
		return this.crdtBy;
	}

	public void setCrdtBy(String crdtBy) {
		this.crdtBy = crdtBy;
	}

	public Serializable getCrdtDtm() {
		return this.crdtDtm;
	}

	public void setCrdtDtm(Serializable crdtDtm) {
		this.crdtDtm = crdtDtm;
	}

	public String getUpdtBy() {
		return this.updtBy;
	}

	public void setUpdtBy(String updtBy) {
		this.updtBy = updtBy;
	}

	public Serializable getUpdtDtm() {
		return this.updtDtm;
	}

	public void setUpdtDtm(Serializable updtDtm) {
		this.updtDtm = updtDtm;
	}

	public Set getSecAppRsrcPerms() {
		return this.secAppRsrcPerms;
	}

	public void setSecAppRsrcPerms(Set secAppRsrcPerms) {
		this.secAppRsrcPerms = secAppRsrcPerms;
	}

	public Set getSecAppRolePerms() {
		return this.secAppRolePerms;
	}

	public void setSecAppRolePerms(Set secAppRolePerms) {
		this.secAppRolePerms = secAppRolePerms;
	}

}
