# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 5bc5b0a34d5abe1bf6a0e043e41cda6fa244fc0d

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: bcds@localhost


swagger:
    title: BCDS API
    description: BCDS applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

server:
    port: 8083

spring:
    profiles:
        active: dev
    datasource:
      driverClassName: oracle.jdbc.OracleDriver
      dataSourceClassName: oracle.jdbc.pool.OracleDataSource
      url: jdbc:oracle:thin:@IBCDS408:1521/DEV.BCDSS
      username: BCDSS
      password: developmentonly
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        database: ORACLE
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: bcds

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

spring.jpa.properties.org.hibernate.envers.audit_table_prefix: AUDIT_
spring.jpa.properties.org.hibernate.envers.audit_table_suffix:
spring.jpa.properties.org.hibernate.envers.default_schema: BCDS
spring.jpa.properties.org.hibernate.envers.do_not_audit_optimistic_locking_field: true
