package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Ah4929RatingDecision generated by hbm2java
 */
public class Ah4929RatingDecision implements java.io.Serializable {

	private Ah4929RatingDecisionId id;

	public Ah4929RatingDecision() {
	}

	public Ah4929RatingDecision(Ah4929RatingDecisionId id) {
		this.id = id;
	}

	public Ah4929RatingDecisionId getId() {
		return this.id;
	}

	public void setId(Ah4929RatingDecisionId id) {
		this.id = id;
	}

}
