package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AudtEvent generated by hbm2java
 */
public class AudtEvent implements java.io.Serializable {

	private BigDecimal eventId;
	private String principal;
	private Serializable eventDate;
	private String eventType;
	private Set audtEventDatas = new HashSet(0);

	public AudtEvent() {
	}

	public AudtEvent(BigDecimal eventId, String principal) {
		this.eventId = eventId;
		this.principal = principal;
	}

	public AudtEvent(BigDecimal eventId, String principal, Serializable eventDate, String eventType,
			Set audtEventDatas) {
		this.eventId = eventId;
		this.principal = principal;
		this.eventDate = eventDate;
		this.eventType = eventType;
		this.audtEventDatas = audtEventDatas;
	}

	public BigDecimal getEventId() {
		return this.eventId;
	}

	public void setEventId(BigDecimal eventId) {
		this.eventId = eventId;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public Serializable getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Serializable eventDate) {
		this.eventDate = eventDate;
	}

	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	public Set getAudtEventDatas() {
		return this.audtEventDatas;
	}

	public void setAudtEventDatas(Set audtEventDatas) {
		this.audtEventDatas = audtEventDatas;
	}

}
