package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

/**
 * AudtEventDataId generated by hbm2java
 */
public class AudtEventDataId implements java.io.Serializable {

	private BigDecimal eventId;
	private String name;

	public AudtEventDataId() {
	}

	public AudtEventDataId(BigDecimal eventId, String name) {
		this.eventId = eventId;
		this.name = name;
	}

	public BigDecimal getEventId() {
		return this.eventId;
	}

	public void setEventId(BigDecimal eventId) {
		this.eventId = eventId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AudtEventDataId))
			return false;
		AudtEventDataId castOther = (AudtEventDataId) other;

		return ((this.getEventId() == castOther.getEventId()) || (this.getEventId() != null
				&& castOther.getEventId() != null && this.getEventId().equals(castOther.getEventId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEventId() == null ? 0 : this.getEventId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
