package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * AudtPersistentToken generated by hbm2java
 */
public class AudtPersistentToken implements java.io.Serializable {

	private String series;
	private SecAppUser secAppUser;
	private String tokenValue;
	private Date tokenDate;
	private String ipAddress;
	private String userAgent;

	public AudtPersistentToken() {
	}

	public AudtPersistentToken(String series, String tokenValue) {
		this.series = series;
		this.tokenValue = tokenValue;
	}

	public AudtPersistentToken(String series, SecAppUser secAppUser, String tokenValue, Date tokenDate,
			String ipAddress, String userAgent) {
		this.series = series;
		this.secAppUser = secAppUser;
		this.tokenValue = tokenValue;
		this.tokenDate = tokenDate;
		this.ipAddress = ipAddress;
		this.userAgent = userAgent;
	}

	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	public SecAppUser getSecAppUser() {
		return this.secAppUser;
	}

	public void setSecAppUser(SecAppUser secAppUser) {
		this.secAppUser = secAppUser;
	}

	public String getTokenValue() {
		return this.tokenValue;
	}

	public void setTokenValue(String tokenValue) {
		this.tokenValue = tokenValue;
	}

	public Date getTokenDate() {
		return this.tokenDate;
	}

	public void setTokenDate(Date tokenDate) {
		this.tokenDate = tokenDate;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

}
