package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DdmCtlg generated by hbm2java
 */
public class DdmCtlg implements java.io.Serializable {

	private BigDecimal ctlgId;
	private String ctlgDesc;
	private Set ddmCntnts = new HashSet(0);
	private Set ddmDiags = new HashSet(0);
	private Set ddmModelPatternIndxes = new HashSet(0);

	public DdmCtlg() {
	}

	public DdmCtlg(BigDecimal ctlgId) {
		this.ctlgId = ctlgId;
	}

	public DdmCtlg(BigDecimal ctlgId, String ctlgDesc, Set ddmCntnts, Set ddmDiags, Set ddmModelPatternIndxes) {
		this.ctlgId = ctlgId;
		this.ctlgDesc = ctlgDesc;
		this.ddmCntnts = ddmCntnts;
		this.ddmDiags = ddmDiags;
		this.ddmModelPatternIndxes = ddmModelPatternIndxes;
	}

	public BigDecimal getCtlgId() {
		return this.ctlgId;
	}

	public void setCtlgId(BigDecimal ctlgId) {
		this.ctlgId = ctlgId;
	}

	public String getCtlgDesc() {
		return this.ctlgDesc;
	}

	public void setCtlgDesc(String ctlgDesc) {
		this.ctlgDesc = ctlgDesc;
	}

	public Set getDdmCntnts() {
		return this.ddmCntnts;
	}

	public void setDdmCntnts(Set ddmCntnts) {
		this.ddmCntnts = ddmCntnts;
	}

	public Set getDdmDiags() {
		return this.ddmDiags;
	}

	public void setDdmDiags(Set ddmDiags) {
		this.ddmDiags = ddmDiags;
	}

	public Set getDdmModelPatternIndxes() {
		return this.ddmModelPatternIndxes;
	}

	public void setDdmModelPatternIndxes(Set ddmModelPatternIndxes) {
		this.ddmModelPatternIndxes = ddmModelPatternIndxes;
	}

}
