package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * DdmModelPatternIndx generated by hbm2java
 */
public class DdmModelPatternIndx implements java.io.Serializable {

	private DdmModelPatternIndxId id;
	private DdmCtlg ddmCtlg;
	private DdmModelPattern ddmModelPattern;

	public DdmModelPatternIndx() {
	}

	public DdmModelPatternIndx(DdmModelPatternIndxId id) {
		this.id = id;
	}

	public DdmModelPatternIndx(DdmModelPatternIndxId id, DdmCtlg ddmCtlg, DdmModelPattern ddmModelPattern) {
		this.id = id;
		this.ddmCtlg = ddmCtlg;
		this.ddmModelPattern = ddmModelPattern;
	}

	public DdmModelPatternIndxId getId() {
		return this.id;
	}

	public void setId(DdmModelPatternIndxId id) {
		this.id = id;
	}

	public DdmCtlg getDdmCtlg() {
		return this.ddmCtlg;
	}

	public void setDdmCtlg(DdmCtlg ddmCtlg) {
		this.ddmCtlg = ddmCtlg;
	}

	public DdmModelPattern getDdmModelPattern() {
		return this.ddmModelPattern;
	}

	public void setDdmModelPattern(DdmModelPattern ddmModelPattern) {
		this.ddmModelPattern = ddmModelPattern;
	}

}
