package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * DdmModelDiag generated by hbm2java
 */
public class DdmModelDiag implements java.io.Serializable {

	private DdmModelDiagId id;
	private DdmDiag ddmDiag;
	private DdmModelPattern ddmModelPattern;

	public DdmModelDiag() {
	}

	public DdmModelDiag(DdmModelDiagId id) {
		this.id = id;
	}

	public DdmModelDiag(DdmModelDiagId id, DdmDiag ddmDiag, DdmModelPattern ddmModelPattern) {
		this.id = id;
		this.ddmDiag = ddmDiag;
		this.ddmModelPattern = ddmModelPattern;
	}

	public DdmModelDiagId getId() {
		return this.id;
	}

	public void setId(DdmModelDiagId id) {
		this.id = id;
	}

	public DdmDiag getDdmDiag() {
		return this.ddmDiag;
	}

	public void setDdmDiag(DdmDiag ddmDiag) {
		this.ddmDiag = ddmDiag;
	}

	public DdmModelPattern getDdmModelPattern() {
		return this.ddmModelPattern;
	}

	public void setDdmModelPattern(DdmModelPattern ddmModelPattern) {
		this.ddmModelPattern = ddmModelPattern;
	}

}
