package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * DdmModelCntnt generated by hbm2java
 */
public class DdmModelCntnt implements java.io.Serializable {

	private DdmModelCntntId id;
	private DdmCntnt ddmCntnt;
	private DdmModelPattern ddmModelPattern;

	public DdmModelCntnt() {
	}

	public DdmModelCntnt(DdmModelCntntId id) {
		this.id = id;
	}

	public DdmModelCntnt(DdmModelCntntId id, DdmCntnt ddmCntnt, DdmModelPattern ddmModelPattern) {
		this.id = id;
		this.ddmCntnt = ddmCntnt;
		this.ddmModelPattern = ddmModelPattern;
	}

	public DdmModelCntntId getId() {
		return this.id;
	}

	public void setId(DdmModelCntntId id) {
		this.id = id;
	}

	public DdmCntnt getDdmCntnt() {
		return this.ddmCntnt;
	}

	public void setDdmCntnt(DdmCntnt ddmCntnt) {
		this.ddmCntnt = ddmCntnt;
	}

	public DdmModelPattern getDdmModelPattern() {
		return this.ddmModelPattern;
	}

	public void setDdmModelPattern(DdmModelPattern ddmModelPattern) {
		this.ddmModelPattern = ddmModelPattern;
	}

}
