package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

/**
 * DdmModelPatternId generated by hbm2java
 */
public class DdmModelPatternId implements java.io.Serializable {

	private BigDecimal patternId;
	private String modelType;

	public DdmModelPatternId() {
	}

	public DdmModelPatternId(BigDecimal patternId, String modelType) {
		this.patternId = patternId;
		this.modelType = modelType;
	}

	public BigDecimal getPatternId() {
		return this.patternId;
	}

	public void setPatternId(BigDecimal patternId) {
		this.patternId = patternId;
	}

	public String getModelType() {
		return this.modelType;
	}

	public void setModelType(String modelType) {
		this.modelType = modelType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DdmModelPatternId))
			return false;
		DdmModelPatternId castOther = (DdmModelPatternId) other;

		return ((this.getPatternId() == castOther.getPatternId()) || (this.getPatternId() != null
				&& castOther.getPatternId() != null && this.getPatternId().equals(castOther.getPatternId())))
				&& ((this.getModelType() == castOther.getModelType()) || (this.getModelType() != null
						&& castOther.getModelType() != null && this.getModelType().equals(castOther.getModelType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPatternId() == null ? 0 : this.getPatternId().hashCode());
		result = 37 * result + (getModelType() == null ? 0 : this.getModelType().hashCode());
		return result;
	}

}
