package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

/**
 * ModelRatingResultsCntntId generated by hbm2java
 */
public class ModelRatingResultsCntntId implements java.io.Serializable {

	private BigDecimal cntntId;
	private BigDecimal processId;
	private BigDecimal count;

	public ModelRatingResultsCntntId() {
	}

	public ModelRatingResultsCntntId(BigDecimal cntntId, BigDecimal processId, BigDecimal count) {
		this.cntntId = cntntId;
		this.processId = processId;
		this.count = count;
	}

	public BigDecimal getCntntId() {
		return this.cntntId;
	}

	public void setCntntId(BigDecimal cntntId) {
		this.cntntId = cntntId;
	}

	public BigDecimal getProcessId() {
		return this.processId;
	}

	public void setProcessId(BigDecimal processId) {
		this.processId = processId;
	}

	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelRatingResultsCntntId))
			return false;
		ModelRatingResultsCntntId castOther = (ModelRatingResultsCntntId) other;

		return ((this.getCntntId() == castOther.getCntntId()) || (this.getCntntId() != null
				&& castOther.getCntntId() != null && this.getCntntId().equals(castOther.getCntntId())))
				&& ((this.getProcessId() == castOther.getProcessId()) || (this.getProcessId() != null
						&& castOther.getProcessId() != null && this.getProcessId().equals(castOther.getProcessId())))
				&& ((this.getCount() == castOther.getCount()) || (this.getCount() != null
						&& castOther.getCount() != null && this.getCount().equals(castOther.getCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCntntId() == null ? 0 : this.getCntntId().hashCode());
		result = 37 * result + (getProcessId() == null ? 0 : this.getProcessId().hashCode());
		result = 37 * result + (getCount() == null ? 0 : this.getCount().hashCode());
		return result;
	}

}
