package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ModelRatingResultsStatusId generated by hbm2java
 */
public class ModelRatingResultsStatusId implements java.io.Serializable {

	private BigDecimal processId;
	private String processStatus;
	private String reason;
	private String crtdBy;
	private Date crtdDtm;

	public ModelRatingResultsStatusId() {
	}

	public ModelRatingResultsStatusId(BigDecimal processId, String processStatus, String reason, String crtdBy,
			Date crtdDtm) {
		this.processId = processId;
		this.processStatus = processStatus;
		this.reason = reason;
		this.crtdBy = crtdBy;
		this.crtdDtm = crtdDtm;
	}

	public BigDecimal getProcessId() {
		return this.processId;
	}

	public void setProcessId(BigDecimal processId) {
		this.processId = processId;
	}

	public String getProcessStatus() {
		return this.processStatus;
	}

	public void setProcessStatus(String processStatus) {
		this.processStatus = processStatus;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getCrtdBy() {
		return this.crtdBy;
	}

	public void setCrtdBy(String crtdBy) {
		this.crtdBy = crtdBy;
	}

	public Date getCrtdDtm() {
		return this.crtdDtm;
	}

	public void setCrtdDtm(Date crtdDtm) {
		this.crtdDtm = crtdDtm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelRatingResultsStatusId))
			return false;
		ModelRatingResultsStatusId castOther = (ModelRatingResultsStatusId) other;

		return ((this.getProcessId() == castOther.getProcessId()) || (this.getProcessId() != null
				&& castOther.getProcessId() != null && this.getProcessId().equals(castOther.getProcessId())))
				&& ((this.getProcessStatus() == castOther.getProcessStatus())
						|| (this.getProcessStatus() != null && castOther.getProcessStatus() != null
								&& this.getProcessStatus().equals(castOther.getProcessStatus())))
				&& ((this.getReason() == castOther.getReason()) || (this.getReason() != null
						&& castOther.getReason() != null && this.getReason().equals(castOther.getReason())))
				&& ((this.getCrtdBy() == castOther.getCrtdBy()) || (this.getCrtdBy() != null
						&& castOther.getCrtdBy() != null && this.getCrtdBy().equals(castOther.getCrtdBy())))
				&& ((this.getCrtdDtm() == castOther.getCrtdDtm()) || (this.getCrtdDtm() != null
						&& castOther.getCrtdDtm() != null && this.getCrtdDtm().equals(castOther.getCrtdDtm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProcessId() == null ? 0 : this.getProcessId().hashCode());
		result = 37 * result + (getProcessStatus() == null ? 0 : this.getProcessStatus().hashCode());
		result = 37 * result + (getReason() == null ? 0 : this.getReason().hashCode());
		result = 37 * result + (getCrtdBy() == null ? 0 : this.getCrtdBy().hashCode());
		result = 37 * result + (getCrtdDtm() == null ? 0 : this.getCrtdDtm().hashCode());
		return result;
	}

}
