package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * ModelRatingResultsCntnt generated by hbm2java
 */
public class ModelRatingResultsCntnt implements java.io.Serializable {

	private ModelRatingResultsCntntId id;
	private DdmCntnt ddmCntnt;
	private ModelRatingResults modelRatingResults;

	public ModelRatingResultsCntnt() {
	}

	public ModelRatingResultsCntnt(ModelRatingResultsCntntId id) {
		this.id = id;
	}

	public ModelRatingResultsCntnt(ModelRatingResultsCntntId id, DdmCntnt ddmCntnt,
			ModelRatingResults modelRatingResults) {
		this.id = id;
		this.ddmCntnt = ddmCntnt;
		this.modelRatingResults = modelRatingResults;
	}

	public ModelRatingResultsCntntId getId() {
		return this.id;
	}

	public void setId(ModelRatingResultsCntntId id) {
		this.id = id;
	}

	public DdmCntnt getDdmCntnt() {
		return this.ddmCntnt;
	}

	public void setDdmCntnt(DdmCntnt ddmCntnt) {
		this.ddmCntnt = ddmCntnt;
	}

	public ModelRatingResults getModelRatingResults() {
		return this.modelRatingResults;
	}

	public void setModelRatingResults(ModelRatingResults modelRatingResults) {
		this.modelRatingResults = modelRatingResults;
	}

}
