package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * MvStgnClaim generated by hbm2java
 */
public class MvStgnClaim implements java.io.Serializable {

	private MvStgnClaimId id;

	public MvStgnClaim() {
	}

	public MvStgnClaim(MvStgnClaimId id) {
		this.id = id;
	}

	public MvStgnClaimId getId() {
		return this.id;
	}

	public void setId(MvStgnClaimId id) {
		this.id = id;
	}

}
