package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;

/**
 * SecAppRsrcPerm generated by hbm2java
 */
public class SecAppRsrcPerm implements java.io.Serializable {

	private SecAppRsrcPermId id;
	private SecAppRsrc secAppRsrc;
	private SecPerm secPerm;
	private String appRsrcPerm;
	private String crdtBy;
	private Serializable crdtDtm;
	private String updtBy;
	private Serializable updtDtm;

	public SecAppRsrcPerm() {
	}

	public SecAppRsrcPerm(SecAppRsrcPermId id, SecAppRsrc secAppRsrc, SecPerm secPerm, String appRsrcPerm,
			String crdtBy, Serializable crdtDtm) {
		this.id = id;
		this.secAppRsrc = secAppRsrc;
		this.secPerm = secPerm;
		this.appRsrcPerm = appRsrcPerm;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
	}

	public SecAppRsrcPerm(SecAppRsrcPermId id, SecAppRsrc secAppRsrc, SecPerm secPerm, String appRsrcPerm,
			String crdtBy, Serializable crdtDtm, String updtBy, Serializable updtDtm) {
		this.id = id;
		this.secAppRsrc = secAppRsrc;
		this.secPerm = secPerm;
		this.appRsrcPerm = appRsrcPerm;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
		this.updtBy = updtBy;
		this.updtDtm = updtDtm;
	}

	public SecAppRsrcPermId getId() {
		return this.id;
	}

	public void setId(SecAppRsrcPermId id) {
		this.id = id;
	}

	public SecAppRsrc getSecAppRsrc() {
		return this.secAppRsrc;
	}

	public void setSecAppRsrc(SecAppRsrc secAppRsrc) {
		this.secAppRsrc = secAppRsrc;
	}

	public SecPerm getSecPerm() {
		return this.secPerm;
	}

	public void setSecPerm(SecPerm secPerm) {
		this.secPerm = secPerm;
	}

	public String getAppRsrcPerm() {
		return this.appRsrcPerm;
	}

	public void setAppRsrcPerm(String appRsrcPerm) {
		this.appRsrcPerm = appRsrcPerm;
	}

	public String getCrdtBy() {
		return this.crdtBy;
	}

	public void setCrdtBy(String crdtBy) {
		this.crdtBy = crdtBy;
	}

	public Serializable getCrdtDtm() {
		return this.crdtDtm;
	}

	public void setCrdtDtm(Serializable crdtDtm) {
		this.crdtDtm = crdtDtm;
	}

	public String getUpdtBy() {
		return this.updtBy;
	}

	public void setUpdtBy(String updtBy) {
		this.updtBy = updtBy;
	}

	public Serializable getUpdtDtm() {
		return this.updtDtm;
	}

	public void setUpdtDtm(Serializable updtDtm) {
		this.updtDtm = updtDtm;
	}

}
