package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

/**
 * SecAppUserRole generated by hbm2java
 */
public class SecAppUserRole implements java.io.Serializable {

	private SecAppUserRoleId id;
	private SecAppUser secAppUser;

	public SecAppUserRole() {
	}

	public SecAppUserRole(SecAppUserRoleId id, SecAppUser secAppUser) {
		this.id = id;
		this.secAppUser = secAppUser;
	}

	public SecAppUserRoleId getId() {
		return this.id;
	}

	public void setId(SecAppUserRoleId id) {
		this.id = id;
	}

	public SecAppUser getSecAppUser() {
		return this.secAppUser;
	}

	public void setSecAppUser(SecAppUser secAppUser) {
		this.secAppUser = secAppUser;
	}

}
