package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;

/**
 * SecAppRole generated by hbm2java
 */
public class SecAppRole implements java.io.Serializable {

	private SecAppRoleId id;
	private String roleDscn;
	private String crdtBy;
	private Serializable crdtDtm;
	private String updtBy;
	private Serializable updtDtm;

	public SecAppRole() {
	}

	public SecAppRole(SecAppRoleId id, String roleDscn, String crdtBy, Serializable crdtDtm) {
		this.id = id;
		this.roleDscn = roleDscn;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
	}

	public SecAppRole(SecAppRoleId id, String roleDscn, String crdtBy, Serializable crdtDtm, String updtBy,
			Serializable updtDtm) {
		this.id = id;
		this.roleDscn = roleDscn;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
		this.updtBy = updtBy;
		this.updtDtm = updtDtm;
	}

	public SecAppRoleId getId() {
		return this.id;
	}

	public void setId(SecAppRoleId id) {
		this.id = id;
	}

	public String getRoleDscn() {
		return this.roleDscn;
	}

	public void setRoleDscn(String roleDscn) {
		this.roleDscn = roleDscn;
	}

	public String getCrdtBy() {
		return this.crdtBy;
	}

	public void setCrdtBy(String crdtBy) {
		this.crdtBy = crdtBy;
	}

	public Serializable getCrdtDtm() {
		return this.crdtDtm;
	}

	public void setCrdtDtm(Serializable crdtDtm) {
		this.crdtDtm = crdtDtm;
	}

	public String getUpdtBy() {
		return this.updtBy;
	}

	public void setUpdtBy(String updtBy) {
		this.updtBy = updtBy;
	}

	public Serializable getUpdtDtm() {
		return this.updtDtm;
	}

	public void setUpdtDtm(Serializable updtDtm) {
		this.updtDtm = updtDtm;
	}

}
