package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SecAppUser generated by hbm2java
 */
public class SecAppUser implements java.io.Serializable {

	private BigDecimal userId;
	private String userNm;
	private String userLogin;
	private String userNtwkId;
	private String pswd;
	private String stas;
	private String crdtBy;
	private Serializable crdtDtm;
	private String updtBy;
	private Serializable updtDtm;
	private String email;
	private Set audtPersistentTokens = new HashSet(0);
	private Set secAppUserRoles = new HashSet(0);

	public SecAppUser() {
	}

	public SecAppUser(BigDecimal userId, String userNm, String userLogin, String pswd, String stas, String crdtBy,
			Serializable crdtDtm) {
		this.userId = userId;
		this.userNm = userNm;
		this.userLogin = userLogin;
		this.pswd = pswd;
		this.stas = stas;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
	}

	public SecAppUser(BigDecimal userId, String userNm, String userLogin, String userNtwkId, String pswd, String stas,
			String crdtBy, Serializable crdtDtm, String updtBy, Serializable updtDtm, String email,
			Set audtPersistentTokens, Set secAppUserRoles) {
		this.userId = userId;
		this.userNm = userNm;
		this.userLogin = userLogin;
		this.userNtwkId = userNtwkId;
		this.pswd = pswd;
		this.stas = stas;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
		this.updtBy = updtBy;
		this.updtDtm = updtDtm;
		this.email = email;
		this.audtPersistentTokens = audtPersistentTokens;
		this.secAppUserRoles = secAppUserRoles;
	}

	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	public String getUserNm() {
		return this.userNm;
	}

	public void setUserNm(String userNm) {
		this.userNm = userNm;
	}

	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	public String getUserNtwkId() {
		return this.userNtwkId;
	}

	public void setUserNtwkId(String userNtwkId) {
		this.userNtwkId = userNtwkId;
	}

	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	public String getStas() {
		return this.stas;
	}

	public void setStas(String stas) {
		this.stas = stas;
	}

	public String getCrdtBy() {
		return this.crdtBy;
	}

	public void setCrdtBy(String crdtBy) {
		this.crdtBy = crdtBy;
	}

	public Serializable getCrdtDtm() {
		return this.crdtDtm;
	}

	public void setCrdtDtm(Serializable crdtDtm) {
		this.crdtDtm = crdtDtm;
	}

	public String getUpdtBy() {
		return this.updtBy;
	}

	public void setUpdtBy(String updtBy) {
		this.updtBy = updtBy;
	}

	public Serializable getUpdtDtm() {
		return this.updtDtm;
	}

	public void setUpdtDtm(Serializable updtDtm) {
		this.updtDtm = updtDtm;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getAudtPersistentTokens() {
		return this.audtPersistentTokens;
	}

	public void setAudtPersistentTokens(Set audtPersistentTokens) {
		this.audtPersistentTokens = audtPersistentTokens;
	}

	public Set getSecAppUserRoles() {
		return this.secAppUserRoles;
	}

	public void setSecAppUserRoles(Set secAppUserRoles) {
		this.secAppUserRoles = secAppUserRoles;
	}

}
