package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SecAppRsrc generated by hbm2java
 */
public class SecAppRsrc implements java.io.Serializable {

	private BigDecimal appRsrcId;
	private String appRsrcNm;
	private String appRsrcDscn;
	private String crdtBy;
	private Serializable crdtDtm;
	private String updtBy;
	private Serializable updtDtm;
	private Set secAppRsrcPerms = new HashSet(0);

	public SecAppRsrc() {
	}

	public SecAppRsrc(BigDecimal appRsrcId, String appRsrcNm, String appRsrcDscn, String crdtBy, Serializable crdtDtm) {
		this.appRsrcId = appRsrcId;
		this.appRsrcNm = appRsrcNm;
		this.appRsrcDscn = appRsrcDscn;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
	}

	public SecAppRsrc(BigDecimal appRsrcId, String appRsrcNm, String appRsrcDscn, String crdtBy, Serializable crdtDtm,
			String updtBy, Serializable updtDtm, Set secAppRsrcPerms) {
		this.appRsrcId = appRsrcId;
		this.appRsrcNm = appRsrcNm;
		this.appRsrcDscn = appRsrcDscn;
		this.crdtBy = crdtBy;
		this.crdtDtm = crdtDtm;
		this.updtBy = updtBy;
		this.updtDtm = updtDtm;
		this.secAppRsrcPerms = secAppRsrcPerms;
	}

	public BigDecimal getAppRsrcId() {
		return this.appRsrcId;
	}

	public void setAppRsrcId(BigDecimal appRsrcId) {
		this.appRsrcId = appRsrcId;
	}

	public String getAppRsrcNm() {
		return this.appRsrcNm;
	}

	public void setAppRsrcNm(String appRsrcNm) {
		this.appRsrcNm = appRsrcNm;
	}

	public String getAppRsrcDscn() {
		return this.appRsrcDscn;
	}

	public void setAppRsrcDscn(String appRsrcDscn) {
		this.appRsrcDscn = appRsrcDscn;
	}

	public String getCrdtBy() {
		return this.crdtBy;
	}

	public void setCrdtBy(String crdtBy) {
		this.crdtBy = crdtBy;
	}

	public Serializable getCrdtDtm() {
		return this.crdtDtm;
	}

	public void setCrdtDtm(Serializable crdtDtm) {
		this.crdtDtm = crdtDtm;
	}

	public String getUpdtBy() {
		return this.updtBy;
	}

	public void setUpdtBy(String updtBy) {
		this.updtBy = updtBy;
	}

	public Serializable getUpdtDtm() {
		return this.updtDtm;
	}

	public void setUpdtDtm(Serializable updtDtm) {
		this.updtDtm = updtDtm;
	}

	public Set getSecAppRsrcPerms() {
		return this.secAppRsrcPerms;
	}

	public void setSecAppRsrcPerms(Set secAppRsrcPerms) {
		this.secAppRsrcPerms = secAppRsrcPerms;
	}

}
