package main.java.gov.va.vba.persistence.models.data;
// Generated Oct 21, 2016 1:08:50 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

/**
 * SecAppUserRoleId generated by hbm2java
 */
public class SecAppUserRoleId implements java.io.Serializable {

	private BigDecimal userId;
	private String userRoleNm;

	public SecAppUserRoleId() {
	}

	public SecAppUserRoleId(BigDecimal userId, String userRoleNm) {
		this.userId = userId;
		this.userRoleNm = userRoleNm;
	}

	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	public String getUserRoleNm() {
		return this.userRoleNm;
	}

	public void setUserRoleNm(String userRoleNm) {
		this.userRoleNm = userRoleNm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SecAppUserRoleId))
			return false;
		SecAppUserRoleId castOther = (SecAppUserRoleId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserRoleNm() == castOther.getUserRoleNm())
						|| (this.getUserRoleNm() != null && castOther.getUserRoleNm() != null
								&& this.getUserRoleNm().equals(castOther.getUserRoleNm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getUserRoleNm() == null ? 0 : this.getUserRoleNm().hashCode());
		return result;
	}

}
